### ISSUE TITLE
Feature Request: Support Docker token authentication

### ISSUE THREAD

**Issue by simonbjorzen-ts** [CybercentreCanada/assemblyline#100]
**Is your feature request related to a problem? Please describe.**
AssemblyLine currently only supports basic authentication towards container registries when getting the available image tags.
Docker registries that are behind authentication follow this scheme: https://docs.docker.com/registry/spec/auth/token/

**Describe the solution you'd like**
Please provide support of checking the latest tags on private container registries using the Docker authentication flow instead of basic auth.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by simonbjorzen-ts** [comment]
Relevant code: 
https://github.com/CybercentreCanada/assemblyline-core/blob/4fc852a07e9ed296e4af0aaa629fccec044b5751/assemblyline_core/updater/helper.py#L83

**Comment by cccs-rs** [comment]
Feature should be included in [4.5.0.11](https://github.com/CybercentreCanada/assemblyline/releases/tag/v4.5.0.stable11) release
