### ISSUE TITLE
Python 3.10+ service base images

### ISSUE THREAD

**Issue by kam193** [CybercentreCanada/assemblyline#101]
**Is your feature request related to a problem? Please describe.**
I'd like to create a service for a tool that requires Python 3.10+ to start.

**Describe the solution you'd like**
I'd like to ask for service base images built for Python 3.10 or newer, maybe using separated tag if backward compatibility is questionable. Thanks to Docker, it's not necessary to move everything at once, and I think the service part doesn't have dependencies that would be strictly related to the Python version.

**Describe alternatives you've considered**
If you would rather not provide official images with newer Python yet, I'll just build them on my own - I assume the Dockerfile from the [service repo](https://github.com/CybercentreCanada/assemblyline-v4-service/blob/master/docker/Dockerfile) should be enough, right?

**Additional context**
Newer python is quicker! ;)

**Comment by cccs-rs** [comment]
Hello! We do have plans to upgrade our base image to support a newer version of Debian and Python but I would recommend for the time being to install the newer version of Python in the Dockerfile for your service as an interim solution for now.

**Comment by kam193** [comment]
Thanks for the answer!

**Comment by kam193** [comment]
FYI: I build [my bases](https://github.com/kam193/assemblyline-services/tree/main/al-service-with-py11) with Python 3.11 based on your Dockerfiles, it works well :)

**Comment by cccs-rs** [comment]
Should be part of the 4.5 release of Assemblyline:
https://github.com/CybercentreCanada/assemblyline/releases/tag/v4.5.0.stable1
