### ISSUE TITLE
OAuth auto_properties with a classification group results in InvalidClassification

### ISSUE THREAD

**Issue by simonbjorzen-ts** [CybercentreCanada/assemblyline#102]
**Describe the bug**
Attempting to use auto_properties to set a classification group on an user throws the error:

```
al-ui-1  | Traceback (most recent call last):
al-ui-1  |   File "/var/lib/assemblyline/.local/lib/python3.9/site-packages/assemblyline_ui/api/v4/authentication.py", line 566, in oauth_validate
al-ui-1  |     data = parse_profile(user_data, oauth_provider_config)
al-ui-1  |   File "/var/lib/assemblyline/.local/lib/python3.9/site-packages/assemblyline_ui/helper/oauth.py", line 138, in parse_profile
al-ui-1  |     classification = cl_engine.build_user_classification(classification, ap_val)
al-ui-1  |   File "/var/lib/assemblyline/.local/lib/python3.9/site-packages/assemblyline/common/classification.py", line 926, in build_user_classification
al-ui-1  |     c12n_2 = self.normalize_classification(c12n_2, skip_auto_select=True)
al-ui-1  |   File "/var/lib/assemblyline/.local/lib/python3.9/site-packages/assemblyline/common/classification.py", line 895, in normalize_classification
al-ui-1  |     lvl_idx, req, groups, subgroups = self._get_classification_parts(c12n, long_format=long_format,
al-ui-1  |   File "/var/lib/assemblyline/.local/lib/python3.9/site-packages/assemblyline/common/classification.py", line 416, in _get_classification_parts
al-ui-1  |     lvl_idx = self._get_c12n_level_index(c12n)
al-ui-1  |   File "/var/lib/assemblyline/.local/lib/python3.9/site-packages/assemblyline/common/classification.py", line 226, in _get_c12n_level_index
al-ui-1  |     raise InvalidClassification("Classification level '%s' was not found in "
al-ui-1  | assemblyline.common.classification.InvalidClassification: Classification level 'GROUP' was not found in your classification definition.
```

Auto properties configuration, using the .* pattern for test:
```yaml
auto_properties: 
          - field: groups
            pattern: .*
            type: classification
            value: GROUP
```

Classification group configuration:
```yaml
groups:
  - name: GROUP
    aliases: []
    auto_select: false
    description: Members of the GROUP
    short_name: GROUP
    solitary_display_name: GROUP
```

**To Reproduce**
1. Log in using OAuth with the configuration above, tested using AzureAD as IDp

**Expected behavior**
The classification group should be added to the user

**Screenshots**
N/A

**Environment (please complete the following information if pertinent):**
 - Assemblyline Version: [4.4.0.55]
 - Browser: Edge

**Additional context**
Looked at the code for myself:

Looking at the classification setting in:
https://github.com/CybercentreCanada/assemblyline-ui/blob/3f7fff0c7e547428f9772055f667b7d37640d944/assemblyline_ui/helper/oauth.py#L138C46-L138C46

Shows me that the property is passed to cl_engine.build_user_classification:
https://github.com/CybercentreCanada/assemblyline-ui/blob/75e0be2233ac0f29e479e3809d1770302dca5741/assemblyline/common/classification.py#L888

Which calls normalize_classification:
https://github.com/CybercentreCanada/assemblyline-base/blob/56ac118e5e7095e00e910ff7dd593b523f17373f/assemblyline/common/classification.py#L871

Which calls _get_classification_parts:
https://github.com/CybercentreCanada/assemblyline-base/blob/56ac118e5e7095e00e910ff7dd593b523f17373f/assemblyline/common/classification.py#L414

And the first thing that does is: lvl_idx = self._get_c12n_level_index(c12n)
Which raises the following error because the level is not found:
```
InvalidClassification("Classification level '%s' was not found in "
                                        "your classification definition." % lvl)
```
Because this error was thrown, it never gets to check for the required tokens and groups in _get_classification_parts.

Thanks :)

**Comment by cccs-sgaron** [comment]
Is that still broken in the new versions?

**Comment by simonbjorzen-ts** [comment]
I'm not sure, I switched over to using dynamic groups and setting the auto_properties type to group instead, which solved the issue.

**Comment by cccs-rs** [comment]
We'll close this issue for now but if the issue still persists and is reproducible, feel free to reopen the issue 😀
