### ISSUE TITLE
Extract service: support for ZSTD archives

### ISSUE THREAD

**Issue by kam193** [CybercentreCanada/assemblyline#104]
**Is your feature request related to a problem? Please describe.**
I'd like to analyze ZSTD archives (https://github.com/facebook/zstd), but AL isn't able to extract them. 

**Describe the solution you'd like**
Extend the extractor service to work with ZSTD, e.g. using https://pypi.org/project/zstandard/

**Describe alternatives you've considered**
There are some projects extending the 7zip with this compression, but I'm not sure if they were a right choice for AL. E.g.: https://github.com/mcmilk/7-Zip-zstd (looks like provides just Windows codecs).

**Additional context**
Filetype detection examples:
Mimetype: application/x-zstd
Magic: Zstandard compressed data (v0.8+), Dictionary ID: None

**Comment by gdesmar** [comment]
Upgrading your core Assemblyline to 4.4.0.58 or higher should make those file identify correctly, and Extract 4.4.0.stable21 should handle those ZStandard files (or any recent core/Extract if you're on the dev branch). If you have a different internal file from a tar file that you think should be handle in the same extraction, I am interested to know. If you test with your own files and it doesn't give the expected result, don't hesitate to contact me on discord, or open/reopen a ticket here!

**Comment by kam193** [comment]
Thank you very much, so far, it works as expected!
