### ISSUE TITLE
Deployment on clusters that are namespace restrictive

### ISSUE THREAD

**Issue by cccs-rs** [CybercentreCanada/assemblyline#105]
**Is your feature request related to a problem? Please describe.**
There can exist deployments where sysadmins don't want to allow service accounts to be able to watch all pods across namespaces. Clusters with this kind of configuration can result to producing this error upon installation/upgrade:

`Error: rendered manifests contain a resource that already exists. Unable to continue with install: could not get information about the resource ClusterRole "assemblyline-scaling-manager-cluster-role" in namespace "": clusterroles.rbac.authorization.k8s.io "assemblyline-scaling-manager-cluster-role" is forbidden: User "system:serviceaccount:assemblyline:admin" cannot get resource "clusterroles" in API group "rbac.authorization.k8s.io" at the cluster scope`

**Describe the solution you'd like**
There currently exists a way in Assemblyline to account for `ResourceQuotas` defined in a namespace as an alternative to using pods/node stats for calculating resource availability for service scaling. We should have a flag implemented add/remove certain cluster roles if they won't/can't be used and also tell Scaler to only use one means of calculating availability or the other.

**Additional context**
https://github.com/CybercentreCanada/assemblyline-helm-chart/pull/63#issuecomment-1726029042
Related PRs: 
 - https://github.com/CybercentreCanada/assemblyline-base/pull/1364
 - https://github.com/CybercentreCanada/assemblyline-core/pull/809

**Comment by cccs-rs** [comment]
Feature included in [4.4.0.stable71](https://github.com/CybercentreCanada/assemblyline/releases/tag/v4.4.0.stable71) release

**Comment by eljeffeg** [comment]
Not sure if this is related, but deploying a new cluster and I got these messages.

3m28s (x61 over 18m)   Warning   FailedGetResourceMetric        HorizontalPodAutoscaler/ui-hpa                 failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from resource metrics API
3m28s (x61 over 18m)   Warning   FailedGetResourceMetric        HorizontalPodAutoscaler/service-server-hpa     failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from resource metrics API
3m28s (x61 over 18m)   Warning   FailedGetResourceMetric        HorizontalPodAutoscaler/internal-ui-hpa        failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from resource metrics API
3m28s (x61 over 18m)   Warning   FailedGetResourceMetric        HorizontalPodAutoscaler/dispatcher-hpa         failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from resource metrics API
3m28s (x61 over 18m)   Warning   FailedGetResourceMetric        HorizontalPodAutoscaler/ingester-hpa           failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from resource metrics API
