### ISSUE TITLE
Phishing heuristic context for DocPreview

### ISSUE THREAD

**Issue by cccs-kevin** [CybercentreCanada/assemblyline#107]
**Is your feature request related to a problem? Please describe.**

It would be nice to have context displayed to the user as to why the following heuristic was raised in the ResultSection:
https://github.com/CybercentreCanada/assemblyline-service-document-preview/blob/e2c01693522eb940cf3f077594f5874dd26fee5a/document_preview/document_preview.py#L157

**Describe the solution you'd like**
Some text describing why the heuristic was raised

**Comment by cccs-rs** [comment]
Enhancement added to [v4.4.0.stable19](https://github.com/CybercentreCanada/assemblyline-service-document-preview/releases/tag/v4.4.0.stable19) release.
