### ISSUE TITLE
Suspicious Command Line Arguments missing data

### ISSUE THREAD

**Issue by cccs-kevin** [CybercentreCanada/assemblyline#108]
**Describe the bug**
The file https://www.virustotal.com/gui/file/b564b2c1e682db9c8683a83d3330e7f03e8ad9c2b76379d6f7dada987ebcd714 contains data from the Exiftool that includes the `Command Line Arguments`:

![image](https://github.com/CybercentreCanada/assemblyline/assets/59843993/03fa9203-fb54-4401-af88-27c2b09618b1)

But when the heuristic is raised for the relative path to cmd.exe being suspicious:

![image](https://github.com/CybercentreCanada/assemblyline/assets/59843993/e0a390e6-dc9c-443c-b0bf-8a0ef6fd4fa6)

I think the `Command Line Arguments` section should also be included in this section.

**To Reproduce**
Run that file in Characterize.4.4.0.12

**Comment by gdesmar** [comment]
I believe the heuristic was created at first to look at the command line arguments, but it got expanded to look at many other things. It could be renamed "Suspicious shortcut elements" to make it clearer.
If the command_line_arguments contained elements that I am flagging (like cmd.exe in this example, or mshta.exe...) it will appear in there. 
I am also using it for the shortcut/web file type, where the word "arguments" doesn't make much sense either.
