### ISSUE TITLE
Diagram showing Containers, DBs and their interaction

### ISSUE THREAD

**Issue by lejeuneretif** [CybercentreCanada/assemblyline#11]
Hi, we would like to know if you have available Diagrams showing the Containers and DBs of Assembly Line, and maybe other component if any, and their interactions.

That would help in understanding the platform Assembly Line.

Assembly Line is split in different repositories: core, base, ui, etc. If it makes sense, can the diagram gather the Components coming from these different parts?

**Comment by cccs-kevin** [comment]
Hey @lejeuneretif,

Thanks for the issue!

Here is the architecture doc as requested! https://cybercentrecanada.github.io/assemblyline4_docs/overview/architecture/

If you have any further questions, join our Discord chat!
