### ISSUE TITLE
load_roles_form_acls called with too few arguments

### ISSUE THREAD

**Issue by LukeL-dev** [CybercentreCanada/assemblyline#110]
**Describe the bug**
`load_roles_form_acls` is called with one instead of the two required arguments here: https://github.com/CybercentreCanada/assemblyline-ui/blob/master/assemblyline_ui/security/oauth_auth.py#L67

```
...
if users:
    return users[0]['uname'], load_roles_form_acls(["R", "W"])
```

`load_roles_form_acls` is defined here https://github.com/CybercentreCanada/assemblyline-base/blob/master/assemblyline/odm/models/user.py#L177 as:

```
def load_roles_form_acls(acls, curRoles):
    ...
```

**Environment:**
 - assemblyline-ui, assemblyline-base current

**Comment by cccs-sgaron** [comment]
Will be fixed by: https://github.com/CybercentreCanada/assemblyline-ui/pull/756
