### ISSUE TITLE
Opposite of Safelist to mark suspicious IoCs/tags

### ISSUE THREAD

**Issue by kam193** [CybercentreCanada/assemblyline#112]
**Is your feature request related to a problem? Please describe.**
AL allows easy marking extracted IoCs (domains, urls) and files to the Safelist. This is then nice for quickly understanding what is not really important, and what should be analyzed.

However, there is no easy way to do an opposite - mark a URL, IP or file as suspicious, and let AL redirect our attention to further submissions containing them.

**Describe the solution you'd like**
Maintaining the same behavior as for safe list, but with an opposite meaning. E.g. suspicious IoCs should be listed at the beginning of the list.

**Describe alternatives you've considered**
Any custom service (or maybe even the TagCheck?) could accomplish this, but it would require an external service to copy the IoC to, and then eventually upgrade signatures in AL. 

**Additional context**
Having such a feature as native as safe list would make it extremely easy to use and to quickly react to new or unsure threats. Marks as safe are easy to add and remove, and here would be the same, improving the collaboration.

**Comment by cccs-sgaron** [comment]
This is actually something we've discussed before internally. We now have a Network IOC Reputation service (NetRep) and we would use a "Bad List" of IOC to store its data. This could also be extended to file hashes as well...

**Comment by gdesmar** [comment]
I'm not sure NetRep would be the best place for file hashes. I think tagcheck is a good place to put it. I do not know if we have this use-case currently, but I think it could be applied to a lot of fields. For example, maybe someone would like to flag every executable that contain a certain PE section, so they could add file.pe.sections.hash to the list and TagCheck would flag it from that point on. I'm assuming the request would be to be able to do right-click on the tag and instead of "Add to safelist" it would be "Add to badlist"? On the tags, and on the hashes in the File Identification section of the File Details page?

**Comment by kam193** [comment]
Thanks for the responces! Yeah, my request is to add it to all places where we now can use the safe list - as well the opportunity to view and modify the list. But I'm not against extending it further, maybe not at once.

I can imagine marking bad tags as malicious or suspicious, as well as being able to easily configure more advanced filters for TagCheck, like combining tags and alerting when a few of them come together. Am I right that it's not currently easily possible, or have I just missed this feature?

**Comment by cccs-sgaron** [comment]
I'm working on this right now. This is the list of associated PRs:

- https://github.com/CybercentreCanada/assemblyline-base/pull/1400
- https://github.com/CybercentreCanada/assemblyline-core/pull/835
- https://github.com/CybercentreCanada/assemblyline-service-server/pull/112
- https://github.com/CybercentreCanada/assemblyline-ui/pull/760
- https://github.com/CybercentreCanada/assemblyline-v4-service/pull/677
- https://github.com/CybercentreCanada/assemblyline-service-utilities/pull/87

**Comment by kam193** [comment]
Thank you!

**Comment by kam193** [comment]
I love this potential feature:
https://github.com/CybercentreCanada/assemblyline-service-badlist/blob/eac00fe2a5ac4fae63a3159424b7ce886b3c98ce/service_manifest.yml#L57-L62

Just fyi - from my experiments, it is crucial to allow configuration of similarity value triggering the heuristic

**Comment by cccs-sgaron** [comment]
> I love this potential feature: https://github.com/CybercentreCanada/assemblyline-service-badlist/blob/eac00fe2a5ac4fae63a3159424b7ce886b3c98ce/service_manifest.yml#L57-L62
> 
> Just fyi - from my experiments, it is crucial to allow configuration of similarity value triggering the heuristic

I was planning a TLSH / SSDEEP proximity search for that. Yes this could be an on/off switch

**Comment by kam193** [comment]
Thanks for implementing this - I've already tested it, and looks working very well!
