### ISSUE TITLE
Core Service Account Role Access

### ISSUE THREAD

**Issue by eljeffeg** [CybercentreCanada/assemblyline#113]
We're using roles to access S3.  S3 traffic in the network space is routed to the interface endpoint transparently and we're using IRSA for auth.  We need to create/modify a K8s ServiceAccount for the relevant pods and add its ID to the IAM role trust config, i.e. `system:serviceaccount:assemblyline:<assemblyline>`.  Since AssemblyLine only has the one service account, `assemblyline-scaling-manager`, this is a challenge.  

We would like to allow specifying: coreServiceAccountName: which will be bound to all the core containers.  Should be possible to add the SA to the deployments since they have a pod spec in the definition.

**Comment by cccs-rs** [comment]
Feature included in [4.4.0.stable71](https://github.com/CybercentreCanada/assemblyline/releases/tag/v4.4.0.stable71) release
