### ISSUE TITLE
Feature Request: Ability to Stop Submission Processing

### ISSUE THREAD

**Issue by ociappara** [CybercentreCanada/assemblyline#117]
**Background**:

As of now, users have the capability to delete a submission while it's still in the processing phase. However, there's no direct feature to stop an ongoing submission from continuing its processing. Users are occasionally experiencing prolonged processing times, with some submissions taking as long as 3 days and still going.

**Request**:

Introduce a feature that allows users to stop the processing of their submissions. This would grant users more control, especially in instances where the processing time exceeds what is reasonable or expected.

**Use Case**:

A user submits content for processing. Realizing either they made a mistake in their submission or the processing is taking longer than anticipated, they wish to halt it to save resources, time, or both, but keep existing results. They'd click a 'Stop Processing' button, which would halt any further actions on that submission.

![image](https://github.com/CybercentreCanada/assemblyline/assets/101556967/2c4135ef-f9e7-4aca-8435-f9f83ddbd89c)

**Comment by cccs-sgaron** [comment]
This is actually what is going on right now. When you delete a submission that is still processing, this tells dispatcher to stop sending this file around and marks the temporary record as to be deleted immediatly. Dispatcher waits for services that are already executing the file to terminate then kills the submission. We have no way to notify the services they should terminate as some of them may be behind a service server.

**Comment by cccs-sgaron** [comment]
Can we close this or is there more to it that I didn't understand?

**Comment by cccs-jp** [comment]
Why would submission be processing for 3 days?

**Comment by ociappara** [comment]
I believe this was an issue with JSJaws, once I disabled the service, and restarted the dispatchers the system recovered. I've has JSJaws disabled for the last week and have not observed this behaviour again. This can be closed from our end.

**Comment by cccs-jp** [comment]
@cccs-kevin
