### ISSUE TITLE
Feature Request: Override Default URL Processing for Enhanced Analysis in Assemblyline

### ISSUE THREAD

**Issue by ociappara** [CybercentreCanada/assemblyline#119]
**Background**:

When we resolve URLs outside of AL, we can grab additional bits of data that help us understand threats better. By feeding this data into Assemblyline, we can get richer insights.

**Feature Description**:

We propose the introduction of a customizable setting in Assemblyline that alters its default URL processing behavior. This change will allow us to, route URLs through our internal systems, enabling the capture of supplementary data, such as PCAPs, and subsequently relay this data back to Assemblyline, facilitating a more in-depth analysis.

Moreover, this feature will be beneficial for users who deal with pre-signed or signed URLs (like SAS URLs). By accommodating these URLs, Assemblyline can fetch content that demands unique authentication mechanisms.

**Comment by cccs-sgaron** [comment]
The URL processing in AL is going through a major change already. Urls submitted to assemblyline wil be directly transfered into a custom file format that will allow you to set a ton of different parameter to alter URL scanning. This will also allow us to passively analyse URL againts known bad URL lists. I'm confident that our upcomming URL patches will help with what you are trying to acheive... I'll put this ticket on hold and if what we came up with is not enough, we can reopen it.
