### ISSUE TITLE
Override scaler "default settings" per service

### ISSUE THREAD

**Issue by kam193** [CybercentreCanada/assemblyline#124]
**Is your feature request related to a problem? Please describe.**
It looks like some `default_settings` from the Scaler configuration, like the maximal `backlog` value, cannot be overridden per service. This creates a bottleneck where services with long-running single task, but capable of multiple parallel execution, slows down the process.

Example: I have a service that sends the file for dynamic analyze on a separated server, and waits for the result. As long as the task (up to a few minutes) isn't finished, all other tasks are waiting. Because the backlog value in the Scaler is set to `100` (fine for other services), the service isn't scaled up to handle more tasks. Lowering the backlog value causes unnecessary scaling of other services.

**Describe the solution you'd like**
I'd like to override the backlog value per service, so I can choose which service is scaled up earlier than others.

**Describe alternatives you've considered**
In this case, the service could possibly work asynchronously and just handle a few tasks in parallel - this would be rather harder to implement, and may require additional modifications.

**Comment by cccs-rs** [comment]
This should already be possible from the UI under the Services page:

![image](https://github.com/CybercentreCanada/assemblyline/assets/62077998/22343b49-c14e-407d-9200-1903ecb5ca86)

These settings are put in place to override the defaults that Scaler has configured.

**Comment by kam193** [comment]
Oh, for some reason, I thought that this option (max queue) will just stop accepting new tasks, and do not override the `backlog` to scale up. Thanks for the explanation!
