### ISSUE TITLE
Manually adjust file type

### ISSUE THREAD

**Issue by kam193** [CybercentreCanada/assemblyline#127]
**Is your feature request related to a problem? Please describe.**
Sometimes the provided file type identification can fail to properly assign the type, e.g. when the file is short or contains an unusual combination. It doesn't mean that the identification is wrong by default, but handling some cases can be tricky.

An example:

A file starting like this:

```python
import setuptools
import requests;
```

was classified as `code/java`, it is however unusual, but fully correct Python code.

**Describe the solution you'd like**
I'd like to be able to explicitly tell AssemblyLine what is the type of the given file.

**Describe alternatives you've considered**
Reporting every failure is nice, but it's hard to expect 100% correctness. 

**Additional context**

**Comment by kam193** [comment]
> So what you want is the ability to force Assemblyline to identify a file a certain way, but what is to say that the type that you are forcing is correct? 

Nothing :D My idea is to have it as an optional mechanism, when I really know what I'm doing

> (There is a method but it is hacky)

My head goes in the direction: set a yara identification rule with the hash of the file. Is it what are you thinking about? ;D

re:sample - [this file](https://inspector.pypi.io/project/mt-testpackage-python/0.0.3/packages/7f/a9/4444bc1d5d9e24b22c1c60f3808d418529eec8a294944e46525e9ea721f3/mt_testpackage_python-0.0.3.tar.gz/mt_testpackage_python-0.0.3/setup.py) was identified as `code/java`

**Comment by gdesmar** [comment]
Another reason to aim toward the goal of a better Identify is that if you have files that are wrongly identified, and you can specify it manually, you also assume that every other user will do the same. On top of it, if your file is extracted from an archive or dynamically downloaded from a server, then you won't be able to help Assemblyline do a good job on the original submission. You could resubmit that file on its own, but you may lose important information from the original submission for further processing. i.e. an eml file that contains a python script that writes a passworded zip file to the folder, the original submission may be able to use information from the eml to open the zip file, but by creating a new submission for the python script, you'll lose that context. That is without taking caching into account. That one is more subtle, but I believe the file type is not part of the caching key for the results.

I don't know how much of a problem it could be for those "one-off", but then one-off could become the norm for certain people. I guess if your instance of AL is used by a single or a few researchers, the whole "users" is not that much of an issue. But think of the global community! 😇

That python setup.py sample has both the mimetype and the magic pointing toward java, that's going to be a rough one. :(

**Comment by kam193** [comment]
I understand, and yeah, I really appreciate the community-oriented approach. It's really nice to see how you support the global effort with the AssemlyLine. I wanted to suggest a solution to an edge-case problem, but if you believe it may turn back against the community, then it's probably better to reject it :)

On the other hand

> that's going to be a rough one. :(

:innocent:

**Comment by cccs-kevin** [comment]
Thanks for the sample! I'll work on identifying it correctly :) In the meantime, I'll close this ticket and comment again with the relevant PR.

**Comment by cccs-kevin** [comment]
This should do it https://github.com/CybercentreCanada/assemblyline-base/pull/1420

**Comment by kam193** [comment]
Thank you!
