### ISSUE TITLE
More flexible update sources configuration

### ISSUE THREAD

**Issue by kam193** [CybercentreCanada/assemblyline#136]
**Is your feature request related to a problem? Please describe.**
The current update sources configuration is quite limited to files from static URLs and git repositories, and it's not always enough if data is not distributed in such a way. There is also no way to set some configuration per update source other than related to the connection.

There are two examples: 
* NSRL dataset used in the official safelist service
  * the service uses some hack to make the url dynamic... but the logic fails as NIST does not publish full db dump _every_ quarter, and the service does not support delta updates. In addition, source-related config about trusted distributors is configured on the service level, even if it's not used for any other sources than NSRL.
* Freshclam configuration for ClamAV (not published service)
  * it requires some special treatment due to rate limits and additional configuration possible, currently I also use some hacks to handle it (e.g. headers as configuration).

**Describe the solution you'd like**
Let's define sources types - keep the standard ones static URL & git repos, and let the services define their own additional types with basic general fields (like URL, auth, CA etc.) and additional configuration as in normal service config. Refactor update service skeleton to choose source handler based on the type - either one of globals, or a specific one registered by the service. The downloading method (with handling of all auth and git config) should be accessible to the service, but not used by default for custom types.

Then, for example, the safelist service could have a specialized NSRL service taking as config base url (e.g. `
https://s3.amazonaws.com/rds.nsrl.nist.gov/RDS/`), the type (e.q. `modern`) and base full dump (e.g. `2023.06`). The service would be then responsible for handling the inital db download, and the deltas later. It could also have the `trusted_distributors` allowing to differ the list between types. 

**Describe alternatives you've considered**
Services currently can still handle special cases by doing a little hacking, or it's always possible to have some additional services pre-processing data and sharing it internally in a way easier to handle by AL.

**Additional context**

**Comment by cccs-rs** [comment]
A variation of this exists where a lot of the configuration is in the service details but is organized in a way the configuration is meant for a particular dependency container (typically an updater).
See [NetRep's configuration](https://github.com/CybercentreCanada/assemblyline-service-netrep/blob/43d830e0a2d8585fb861457383fae0c2d8adad88/service_manifest.yml#L57) as an example

We've discussed the idea of having metadata attached to update sources to instruct the updater that the sources should be treated differently from one another and that they have different ways of getting/parsing the data of interest.

As for Safelist, it could be configured in a similar way where you can specify the base DB and it can start looking for deltas from that initial point (that particular configuration would require persistence of the database otherwise it'll waste a lot of time if the container reboots).

As for ClamAV, I think having different update periods per source rather than a global could be useful to handle the rate-limiting use-case.

**Comment by kam193** [comment]
> As for ClamAV, I think having different update periods per source rather than a global could be useful to handle the rate-limiting use-case.

It can be helpful, but probably more important is that for unofficial signatures, you can just download them. For the official one, the high traffic control is in place, and you should use DNS check to download just the diff. Basically, not a thing to be just downloaded via URL. I'm [delegating this](https://github.com/kam193/assemblyline-services/blob/1a460e26c9061d66a92f24a2a10d6c48d926981c/clamav-service/service/updater.py#L78) to the official updater software

**Comment by kam193** [comment]
Adding just a little new use case: I'm considering adding a new source to the badlist service, what currently requires editing the service configuration to instruct the updater. However, if I did that, then this configuration would be marked as changed, so any further upstream changes from your side won't be automatically applied. It's probably not a big deal, it doesn't change often I think, but if we could decouple it from service config and attach to each source independently, it would be more flexible.

**Comment by cccs-rs** [comment]
Yup, this was something I was considering to do if there were more reason to make adding metadata/configuration to update sources rather than as something disjoint that you have to configuration as a service configuration

**Comment by cccs-rs** [comment]
This should be resolved in the [4.5.0.66](https://github.com/CybercentreCanada/assemblyline/releases/tag/v4.5.0.stable66) release and all services built under this release.

**Comment by kam193** [comment]
OMG, now I need to rewrite all the special treatments I wrote, and I don't have time for that, why do you do it to me? :scream:

**Comment by cccs-rs** [comment]
This should help save you from rewriting until the appropriate time you want to transition over, sorry if this broke anything! 😭
https://github.com/kam193/assemblyline-services/pull/1

**Comment by kam193** [comment]
Haha, thank you a lot <3 I really love the change, it was a big missing feature ;)

BTW, hove you already updated all services to respect changes? I've notices that ConfigExtractor updater was trying to pull a disabled source (but maybe my service version `4.5.0.30` isn't the newest?)

**Comment by cccs-rs** [comment]
Yup, all services with updater dependencies should've been updated with respect to these changes. The latest version of ConfigExtractor should be `4.5.0.32`.

**Comment by kam193** [comment]
Ah, okay, than my caching proxy didn't get it yet :D
