### ISSUE TITLE
Wrongly assigned file type "resource/unity" stopped workflow

### ISSUE THREAD

**Issue by kam193** [CybercentreCanada/assemblyline#138]
**Describe the bug**
Some tar.gz archives get the type "resource/unity", and as so, all services for archives, including the extractor, are skipped. 

**To Reproduce**
1. Submit the file, e.g. https://files.pythonhosted.org/packages/b4/69/c90026d54d94f3136c84ac40e8f7cc8ab47356e51c5ec72a564edade7413/physicsml-0.0.0a1.tar.gz
2. Wait for file type assignment.
3. Observe the submission was finished without extracting files.

**Expected behavior**
Assigning the archive/gzip type and extracting the content.

**Screenshots**
![obraz](https://github.com/CybercentreCanada/assemblyline/assets/8472271/25362ae5-1f5f-4849-9f12-0e5243e44d50)

**Environment (please complete the following information if pertinent):**
 - Assemblyline Version: 4.0.0.stable79

**Additional context**

**Comment by gdesmar** [comment]
File identification for resource/unity has been deleted. It will be part of the next release. Thank you for bringing it up!

**Comment by kam193** [comment]
Thanks!
