### ISSUE TITLE
Services headers are dropped in the dev environment

### ISSUE THREAD

**Issue by gdesmar** [CybercentreCanada/assemblyline#140]
**Describe the bug**
Since pinning of Flask/Werkzeug  to 2.3.3, the dev setup cannot have any services deployed as the services are using headers containing underscores: [Task handler headers](https://github.com/CybercentreCanada/assemblyline-service-client/blob/master/assemblyline_service_client/task_handler.py#L102-L106).
There may be more places where headers are set, and underscore being used, but this was the place that was causing the service issue in dev.

**Current workaround**
At start time of the dev instance, we can install an older version of Werkzeug, i.e. 2.2.0, and the underscore are going to work in dev mode. I do not know which version exactly the change was done in Werkzeug.

**Additional context**
[Werkzeug 2.3.3 development server drops headers with underscores](https://github.com/pallets/werkzeug/issues/2693)

**Comment by cccs-sgaron** [comment]
Fix by this patch: https://github.com/CybercentreCanada/assemblyline-service-server/pull/119
