### ISSUE TITLE
Handle unusual 'version' in YARA rules

### ISSUE THREAD

**Issue by kam193** [CybercentreCanada/assemblyline#142]
**Describe the bug**
When a yara rules 'version' does not contain a non-numeric (...) version, the updater fails with a not-really-useful message: `could not convert string to float: ''`.

Side note: I'd suggest adding a logging adapter to put a field with signature identification in case of any log. 

**To Reproduce**
1. Add https://github.com/Neo23x0/signature-base as a YARA rules source.
2. Use a generic regex `.*\.yar$`
3. Observe updater logs and look for: `Problem with neo23x0: could not convert string to float: ''`
4. Observe issues and not importing any signature.

Please ignore problems with undefined identifiers, they are handled correctly.

Then, let's go to the workaround.

1. Set the regex to be: `^.*/yara/(?:(?!hktl_bruteratel_c4).)+\.yar$`, what excludes the following file: https://github.com/Neo23x0/signature-base/blob/1118df54548785ba46c92db66e60aa6e94e824cb/yara/hktl_bruteratel_c4.yar#L5
2. Observe rules imported and update finished successfully. If you still see the error, restart updater service - config wasn't refreshed.

**Expected behavior**
The rule is imported even if the metadata looks unusual. 

**Screenshots**

**Environment (please complete the following information if pertinent):**
 - Assemblyline Version: 4.4.0.stable79, YARA 4.4.0.stable25

**Additional context**

**Comment by cccs-rs** [comment]
The service expects the YARA rules fetched/used to conform to (or at the very least not be in conflict with) [CCCS' metadata spec](https://github.com/CybercentreCanada/CCCS-Yara), hence why you'll notice there are only two sources given officially.

Some of the metadata in the spec is what allows certain rules to assign a score and without such meta, you'll still have a section with match information but will all be declared informational.

The current process of adding more rules to the service is to store a copy of the rules with the metadata changes and pull them in (if let's say the original rules were open source).
I do have plans of adding a script to the `cccs-yara` package that will allow automatic metadata conversion/enrichment so it will make it easier to add new sources at will to Assemblyline.

**Comment by kam193** [comment]
I got it, it makes sense if you wish to enforce the format leveraging more AL features. But as I see, the current behavior is to [remove incorrect rules](https://github.com/CybercentreCanada/assemblyline-service-yara/blob/c63a465e25a287c6ea59675b1f694961e736d5b8/yara_/helper.py#L196). In my case, the rule isn't removed, but causes the whole update process to fail. Maybe we can implement a validation if the rule is not in conflict with the specification, similarly to YARA syntax check, and just remove the failing rule?

**Comment by cccs-rs** [comment]
In this case, it seems that the extracted version is just a null value. In this case, I can let the value assigned go back to the default (`1`).

I don't see a reason to have the rule dropped in this case, as it's just metadata of the rule that doesn't really have an impact on the analysis.

**Comment by cccs-rs** [comment]
This should be patched in the [v4.4.0.stable27](https://github.com/CybercentreCanada/assemblyline-service-yara/releases/tag/v4.4.0.stable27) release of the YARA service.
