### ISSUE TITLE
Allow controlling the threads ration/number in Suricata

### ISSUE THREAD

**Issue by kam193** [CybercentreCanada/assemblyline#143]
**Is your feature request related to a problem? Please describe.**
I run AL in Docker Compose on a VM. It has a couple of vCPUs assigned to handle the whole system. However, Suricata starts several threads, and the number depends on the number of CPUs, currently hard-coded in the service as 1.0 ratio.

Finally, it results in many threads, increasing CPU and memory usage more than reasonable. I suspect it also causes a few kills, but here I'm not sure.

**Describe the solution you'd like**
I'd like to be able to set the `threading.worker-cpu-ratio` [here](https://github.com/CybercentreCanada/assemblyline-service-suricata/blob/3fc62723c779e7a320e7c42495f269fda8d58e35/suricata_/conf/suricata.yaml#L1533) or other related settings.

**Describe alternatives you've considered**
1. Allow setting the `threading.cpu-affinity.worker-cpu-set.threads` to overcome the ratio ([here](https://github.com/CybercentreCanada/assemblyline-service-suricata/blob/3fc62723c779e7a320e7c42495f269fda8d58e35/suricata_/conf/suricata.yaml#L1514))
2. More general solution: take a JSON and merge it with the default settings, basically allowing overwriting most of them, and increasing the flexibility. 

**Additional context**

**Comment by cccs-rs** [comment]
Service configuration (`suricata_conf`) should be part of [4.4.0.stable31](https://github.com/CybercentreCanada/assemblyline-service-suricata/releases/tag/v4.4.0.stable31) release of the Suricata service.

The configuration will perform a dictionary update of the YAML configuration that's stored in the container.
So if you wanted to update `threading.worker-cpu-ratio` then you can set `suricata_conf` to:
`{"threading": { "worker-cpu-ratio": "2.0"}}`

**Comment by kam193** [comment]
Thanks! It's the perfect solution
