### ISSUE TITLE
[feature request] related submissions

### ISSUE THREAD

**Issue by gmolveau** [CybercentreCanada/assemblyline#15]
Hi,

when inspecting a submission, it would be helpful to have the list of related submissions.
And for each file of the submission, add the list of related submissions as well.

For example :

```
Submission_A : file1, file2, file3
Submission_B : file2
Submission_C : file3

related submissions of Submission_A : [Submission_B, Submission_C]
related submissions of file2 : [Submission_A, Submission_B]
```

This way an analyst can easily see if a file has already been seen elsewhere and quickly map the relationships.

This feature would impact the endpoint `/api/v4/submission/report/<sid>/` and the front-end I believe :

```
GET /api/v4/submission/report/<submission_id_A>/
{
    "api_response": {
        ...,
        "related_submissions": ["<sid_B>", "<sid_C>"],
        "file_tree": {
            "sha256_file2": {
                "related_submissions": ["<sid_B>"],
                ...
            }
        }
    }
}
```

or maybe another endpoint should be created.

Thank's !

**Comment by cccs-sgaron** [comment]
This would be costly to find out. As a single query for each files would have to be created.
