### ISSUE TITLE
ASL Yara Signature Updater Invalid Escape Sequence Error

### ISSUE THREAD

**Issue by bobbyD12** [CybercentreCanada/assemblyline#152]
The ASL Yara and Config Extractor service encounters an "Invalid Escape Sequence Error" when processing rules containing `\r` in any string. This issue is caused by a known bug in plyara, as its default escaped strings don't include `r` (refer to [plyara issue #123](https://github.com/plyara/plyara/issues/123)).
To address this, include `r` in the `STRING_ESCAPE_CHARS` of plyara. This can be done by modifying the parser after the parser is created:
```python
parser = Plyara()
parser.STRING_ESCAPE_CHARS.add('r')
```
Given that plyara is no longer actively maintained, we request an implementation of this fix directly within the ASL Yara and Config Extractor service.

**Comment by cccs-rs** [comment]
This should be resolved in the latest stable releases of the Assemblyline services: YARA, TagCheck, and ConfigExtractor.

Thanks for raising the bug to our attention and providing a fix we could implement! 😀
