### ISSUE TITLE
Unable to run docker compose

### ISSUE THREAD

**Issue by znbytedance** [CybercentreCanada/assemblyline#157]
**Describe the bug**
while running the following command

`sudo docker-compose build
[+] Building 0.7s (8/8) FINISHED                                                                           docker:default
 => [updater internal] load build definition from Dockerfile                                                         0.0s
 => => transferring dockerfile: 174B                                                                                 0.0s
 => [updater internal] load .dockerignore                                                                            0.0s
 => => transferring context: 2B                                                                                      0.0s
 => [scaler internal] load metadata for docker.io/cccs/assemblyline-core:4.4.stable                                  0.4s
 => [scaler internal] load build definition from Dockerfile                                                          0.0s
 => => transferring dockerfile: 174B                                                                                 0.0s
 => [scaler internal] load .dockerignore                                                                             0.0s
 => => transferring context: 2B                                                                                      0.0s
 => [updater] importing cache manifest from cccs/assemblyline-core:4.4.stable                                        0.0s
 => CACHED [scaler 1/2] FROM docker.io/cccs/assemblyline-core:4.4.stable@sha256:2ec349df19abc8d60e1fa3b5b24785fd8c4  0.0s
 => ERROR [scaler 2/2] RUN ln -s /var/lib/assemblyline/.local /root/.local                                           0.2s
------
 > [scaler 2/2] RUN ln -s /var/lib/assemblyline/.local /root/.local:
0.147 exec /bin/sh: exec format error
------
failed to solve: process "/bin/sh -c ln -s /var/lib/assemblyline/.local /root/.local" did not complete successfully: exit code: 1
`
followed the deployment guide on: https://cybercentrecanada.github.io/assemblyline4_docs/installation/deployment/

**Comment by cccs-rs** [comment]
Hello! 

Is it possible you're building the Assemblyline container images on a non-amd64 system? 

When [looking up the error raised](https://www.google.com/search?q=docker+build+%2Fbin%2Fsh%3A+exec+format+error), a lot of results pertain to building a container image on a host using an unsupported platform.

In [DockerHub](https://hub.docker.com/layers/cccs/assemblyline-core/4.4.stable/images/sha256-2ec349df19abc8d60e1fa3b5b24785fd8c43d42b19ca6fbf607bc3562cee67f0?context=explore), you'll see that the images we have created are targetting `linux/amd64` platforms only at the moment so I can imagine if there was platform incompatibility it's possible for it to yield the error you saw even when following the documentation.

Any information that you can provide about your deployment environment will help better diagnose the issue.

**Comment by znbytedance** [comment]
Hi, Yes this was the issue.
