### ISSUE TITLE
Importing yara rules: comment treated as "include" statement

### ISSUE THREAD

**Issue by kam193** [CybercentreCanada/assemblyline#158]
**Describe the bug**
I'm trying to configure rule sets from https://yarahq.github.io/

It looks like the function `replace_include` is called on every line starting with `include`, even if it's just a comment.

**To Reproduce**
1. Go to Update sources.
2. Configure new YARA source with https://github.com/YARAHQ/yara-forge/releases/latest/download/yara-forge-rules-core.zip as an URL 
3. Save and wait till updated
4. See error `'NoneType' object has no attribute 'group'`

**Expected behavior**
Rules are imported

**Environment (please complete the following information if pertinent):**
 - Assemblyline Version: 4.4.0.88
 - YARA service: 4.4.0.30

**Additional context**
The file contains two lines starting with `include`, both are comments with the license:

`included in conveying the object code work.` (41388)
`includes interface definition files associated with source files for` (41234)

If I removed them, signatures are correctly imported.

PS. I also tried to go with `extended` rule set, but it produced errors I wasn't able to easily identify, so I assume some rules there aren't comply with CCCS standard

**Comment by cccs-rs** [comment]
Should be fixed in the latest stable release of the service.
