### ISSUE TITLE
Disabling sources without removing it

### ISSUE THREAD

**Issue by kam193** [CybercentreCanada/assemblyline#159]
**Is your feature request related to a problem? Please describe.**
Sporadically I see a signature source producing incorrect files, being just an experiment, or I try to identify an issue with source updates. I'd like to be able to temporary disable a source but without removing the configuration at all, so I could easily re-enable it.

**Describe the solution you'd like**
A enable/disable button in update source details.

**Describe alternatives you've considered**
Removing source is what I do now, but sometimes it's a little irritating to fill again all fields a few times when working on an issue etc. 

**Additional context**

**Comment by cccs-rs** [comment]
This should be resolved in the [4.5.0.66](https://github.com/CybercentreCanada/assemblyline/releases/tag/v4.5.0.stable66) release and all services built under this release.
