### ISSUE TITLE
Feature Request: Blacklist services from running if submitted file is at certain TLP

### ISSUE THREAD

**Issue by C-Oliver** [CybercentreCanada/assemblyline#16]
If a user is submitting a file at TLP:R or TLP:R//[context] we should be able to blacklist services from running on such submissions, even if a user has requested to run that service. This will allow us to introduce riskier services without increasing risk.

**Comment by cccs-sgaron** [comment]
We will keep the default_classification of the service which dictate the at which classification level the service writes its results but will introduce a minimum classification to each service (default TLP:C) that will dictate what is the minimum classification you must have to even see that the service exists. The system will enforce that the default classification will be at least the minimum classification.

**Comment by cccs-rs** [comment]
Fixed in [Release 4.4.0.21](https://github.com/CybercentreCanada/assemblyline/releases/tag/v4.4.0.stable21)
