### ISSUE TITLE
ValueError: invalid literal for int with base 10 when manually clearing service scale values

### ISSUE THREAD

**Issue by jasper-vdhoven** [CybercentreCanada/assemblyline#161]
**Describe the bug**
Setting the number of instances to a custom value,  saving this value, then clearing the value and saving will display a stack trace pop-up as listed in the title.

**To Reproduce**
1. Navigate to any service configuration page, for example TagCheck
2. Change the place holder value "no limit" to any number, such as 2
3. Save the made changes
4. Re-open the TagCheck service settings and clear the set value
5. Save the change and a stack trace should appear

**Expected behavior**
When clearing a set value, I expected it to revert to the default/ place holder value of "no limit"

**Screenshots**
![image](https://github.com/CybercentreCanada/assemblyline/assets/22278716/c0542405-9ebf-4c1a-a3ca-525bdf18e944)
The image above displays the generated stack trace when saving the TagCheck service configuration with the invalid value.

**Environment (please complete the following information if pertinent):**
 - Assemblyline Version: 4.4 stable (Docker single instance)
 - Browser: Firefox

**Comment by cccs-rs** [comment]
This should be resolved in [v4.4.0.stable53](https://github.com/CybercentreCanada/assemblyline-ui-frontend/releases/tag/v4.4.0.stable53) and forward, feel free to re-open the issue if needed.
