### ISSUE TITLE
Make hash searches case-insensitive

### ISSUE THREAD

**Issue by derrickb11** [CybercentreCanada/assemblyline#164]
**Describe the bug**
When submitting hashes with upper case characters to the /api/v4/hash_search/ endpoint, AL responds with 'Invalid Hash'. But submitting with lower case characters works.

**To Reproduce**

1. Submit hash with upper case characters to /api/v4/hash_search/

**Expected behavior**
Hashes with upper case characters are not invalid and should get a response.

**Screenshots**
N/A

**Environment (please complete the following information if pertinent):**
N/A

**Additional context**
N/A

**Comment by cccs-rs** [comment]
This feature should included in [4.5.0.12](https://github.com/CybercentreCanada/assemblyline/releases/tag/v4.5.0.stable12).
