### ISSUE TITLE
Submissions: Fetch files with SHA1/MD5

### ISSUE THREAD

**Issue by scottpas** [CybercentreCanada/assemblyline#168]
**Is your feature request related to a problem? Please describe.**
Currenly, AssemblyLine allows searching by SHA256 on VirusTotal by specifying a [Sha256Source](https://cybercentrecanada.github.io/assemblyline4_docs/odm/models/config/#sha256source). Some EDRs and other sources of data only provide SHA1/MD5 hashes. It would be great to have the option to submit a file by SHA1/MD5 hash as an alternative.

**Describe the solution you'd like**
Expand upon the existing submission config to add SHA1/MD5 hash collection functionality.

**Describe alternatives you've considered**
It's quite possible to obtain SHA256 hashes by looking up the SHA1/MD5 in other data sources (e.g. VirusTotal), but this becomes a quite costly for VirusTotal API quotas. I've been using VirusTotal's API to get and submit [download URLs](https://virustotal.readme.io/reference/files-download-url), but with the recent URLDownloader changes, it adds an extra file to the submission results which becomes quite a pain (two submissions of the same file have different root file hashes, and seeing the VT download URLs in alerts and whatnot is quite annoying)

**Comment by cccs-rs** [comment]
This should be patched in the [4.5.0.20](https://github.com/CybercentreCanada/assemblyline/releases/tag/v4.5.0.stable20) release of Assemblyline.
