### ISSUE TITLE
missing "original_selected" field in notification queue

### ISSUE THREAD

**Issue by cccs-douglass** [CybercentreCanada/assemblyline#17]
Users report that notification queue objects had a field "original_selected" set in the submission parameters which is now missing. 

This was probably supplementary information being added by ingester for resubmits. Check if that was the case and if so, look into making sure the information is still available in some way when the notification is published by the new post-processing module.

**Comment by cccs-sgaron** [comment]
Was this fixed?

**Comment by cccs-douglass** [comment]
I don't think so.

**Comment by cccs-sgaron** [comment]
Do we still need this?
