### ISSUE TITLE
Feature Request: (Badlist) Allow setting expiration time on Badlist IOCs

### ISSUE THREAD

**Issue by simonbjorzen-ts** [CybercentreCanada/assemblyline#193]
**Is your feature request related to a problem? Please describe.**
It would be helpful to be able to set an expiration for IOCs for the Badlist service.

**Describe the solution you'd like**
Allow setting a duration that an IOC is valid for if it disappears from the update source.

**Describe alternatives you've considered**
Sync mode does not fulfill our needs, as some feeds only contain one day of history, but we may want to match against a week old IOCs.

**Additional context**
N/A

**Comment by cccs-sgaron** [comment]
This is a feature already available in the system: 
![image](https://github.com/CybercentreCanada/assemblyline/assets/59840781/6416043c-98aa-452c-93f5-4f238864c591)

**Comment by simonbjorzen-ts** [comment]
How can I set this on an IOC from an external source/feed?

**Comment by simonbjorzen-ts** [comment]
That sounds like what we would need, the ability to be able to set retention time for the external source.
Can we re-open this issue with than goal?

**Comment by cccs-rs** [comment]
How would you want to handle competing sources raising the same item to be added to the badlist and they both can control the expiration?

Should the one with the longer expiry win, should the source with more recent updates win?

**Comment by cccs-sgaron** [comment]
I'd say longer expiry wins as there is an expectation that the IOC will be there for at least that long.

**Comment by cccs-rs** [comment]
Should be patched in the latest version of the service
