### ISSUE TITLE
bug in assemblyline charts with release 4.5.stable

### ISSUE THREAD

**Issue by macit42** [CybercentreCanada/assemblyline#195]
**Describe the bug**
Latest commits for release 4.5 on https://github.com/CybercentreCanada/assemblyline-helm-chart introduces a bug on the `assemblyline` helm chart:

```
$ helm template ./assemblyline -f ./assemblyline/values.yaml

Error: template: assemblyline/templates/jobs.yaml:111:11: executing "assemblyline/templates/jobs.yaml" at <include "assemblyline.coreMounts" .>: error calling include: template: assemblyline/templates/_helpers.tpl:113:13: executing "assemblyline.coreMounts" at <.Values.useReplay>: can't evaluate field Values in type string
```
**To Reproduce**
1. ` git clone https://github.com/CybercentreCanada/assemblyline-helm-chart`
2. `cd assemblyline-helm-chart`
3. `helm template .\assemblyline\ -f .\assemblyline\values.yaml`

**Comment by cccs-rs** [comment]
Seems to be a context related issue when you autoInstallServices, `.` means two different things depending on where it's used at that the time of creating Jobs, it's being used as a string to iterate over a range but the helper template is expecting a dict/map

**Comment by cccs-rs** [comment]
Should be fixed in the latest commit to the helm chart.
