### ISSUE TITLE
Service Manifest Typo - DeobfuScripter & Swiffer

### ISSUE THREAD

**Issue by malvidin** [CybercentreCanada/assemblyline#196]
Typo in `privileged` in two services causes Assemblyline to ignore that setting.

```yaml
privilged: true
# Should be
privileged: true
```

https://github.com/CybercentreCanada/assemblyline-service-deobfuscripter/blob/a91786936b25eeb95b7c39115dfb46357263ce1b/service_manifest.yml#L18

https://github.com/CybercentreCanada/assemblyline-service-swiffer/blob/c217ba5c80cb893d411d47fb49566ff7a1a9f380/service_manifest.yml#L19

If the service is removed and re-added with the correct spelling, "Run service in privileged mode" is set correctly.

**Comment by cccs-rs** [comment]
Should be corrected now in new builds of the services
