### ISSUE TITLE
Deobfuscripter missed obvious IoC

### ISSUE THREAD

**Issue by kam193** [CybercentreCanada/assemblyline#197]
**Describe the bug**
I got a file (attached, it was publicly available) containing a Python code and a suspicious part encoded with base64. Deobfuscator properly revealed the hidden code, but doesn't extract the IP as IoC. Instead, two strange domains were extracted - and I cannot find any part of the file matching them.

**To Reproduce**
1. Process this file: [65a2fb892a53b5271a27f63e22236c189491976eef41c7aa92d80e61e9b82606.zip](https://github.com/CybercentreCanada/assemblyline/files/14364470/65a2fb892a53b5271a27f63e22236c189491976eef41c7aa92d80e61e9b82606.zip) (pass: zippy)
2. Look at deobfuscation results. They should present the final layer like this:
![image](https://github.com/CybercentreCanada/assemblyline/assets/8472271/8e1d9abd-cbc7-4336-9dad-9634c99f3986)
and the IoCs like:
![image](https://github.com/CybercentreCanada/assemblyline/assets/8472271/ad6b211e-4775-4462-8b32-596830185828)
4. Neither the IP nor the full URL shown in the deobfuscated code are presented as IoC. Extracted domains aren't in the file.

**Expected behavior**
IP address is extracted from the obfiscated code.

**Environment (please complete the following information if pertinent):**
 - Assemblyline Version: 4.4.0stable91, DeobfuScripter 4.4.0.23 in privileged mode.

**Comment by cccs-jh** [comment]
Hi, Thank you for reporting this.

The domain false positives are actually found in the file, DeobfuScripter checks for reversed text in the file layer. It is confusing the imports `os.path.exists` and `os.environ` for domains because `.so` is the top level domain of Somalia. I'll try to stop that from happening.

**Comment by kam193** [comment]
Ah, I understand, it makes sense. I think that the most important would be to extract the missed IP, dealing with those FPs is nice, but it's not possible to filter out everything.

**Comment by cccs-jh** [comment]
Both of the issues should now be fixed in the new v4.5.0.stable2 release.
