### ISSUE TITLE
EBook document preview

### ISSUE THREAD

**Issue by gdesmar** [CybercentreCanada/assemblyline#204]
Following the addition of EPUB and Mobi identification (issue #203), it would be great to have a preview of the first page in document preview.
EPUB examples are easy to find, but I relied on those sites for Mobi and AZW3 files to test:
https://filesamples.com/formats/mobi
https://filesamples.com/formats/azw3

Currently, Mobi and AZW3 files are identified as document/mobi, so hopefully we can find a tool that renders both since Mobi is the base for the AZW3 file format.

**Comment by cccs-rs** [comment]
Support for rendering EPUB and MOBI file types added to latest version of DocumentPreview service.
