### ISSUE TITLE
Sorting extracted files

### ISSUE THREAD

**Issue by kam193** [CybercentreCanada/assemblyline#207]
**Is your feature request related to a problem? Please describe.**
Extracted files aren't currently presented in any particular order. As so, if there are more extracted files, navigation through them isn't the best experience.

**Describe the solution you'd like**
I'd like to see files sorted alphabetical. If a file was extracted more than a one time, using _any_ name would be fine. To keep the results stable, it could also be the first name in alphabetical order.

**Describe alternatives you've considered**
One can also think if letting the user manipulate the file tree won't be useful, e.g. by adding more sorting options or file type filter.

**Additional context**
Here is an example comparing the tree in AL, and the archive structure as seen by the Extractor. The tree also includes files generated by other services, which is fine.
![obraz](https://github.com/CybercentreCanada/assemblyline/assets/8472271/07074636-3835-405b-b773-b43f1ff99abb)

**Comment by cccs-rs** [comment]
This should be patched in [4.5.0.15](https://github.com/CybercentreCanada/assemblyline/releases/tag/v4.5.0.stable15) release

**Comment by kam193** [comment]
Thank you!
