### ISSUE TITLE
Allow setting some metadata when manually submitting a file

### ISSUE THREAD

**Issue by kam193** [CybercentreCanada/assemblyline#211]
**Is your feature request related to a problem? Please describe.**
The API allows us to flexible set metadata of a submission, but it's not possible when manually submitting data. I usually fill them when automatically uploading files via API, but occasionally, I want to analyze files intentionally skipped by the automation. I miss then the ability to mark and correlate them. 

In another context, if you have a separated ticketing system and manually upload related data, you would like to add a related ticket ID to easily connect them.

**Describe the solution you'd like**
I'd suggest letting administrators configure metadata fields that can be filled during the manual upload. 

**Describe alternatives you've considered**
* Letting declare any metadata field, as in API - but this would quickly lead to a big mess.
* Marking some metadata as required - it could be interesting, a ticket ID is a great example here.
* More complex validation, e.g. declaring a field with a list of allowed values - interesting but in my opinion, too much work if not being explicitly requested

**Additional context**

**Comment by cccs-rs** [comment]
This should now be featured in the [4.5.0.27](https://github.com/CybercentreCanada/assemblyline/releases/tag/v4.5.0.stable27) release.

**Comment by kam193** [comment]
Great, thanks! I'll test it soon
