### ISSUE TITLE
Cannot submit archived expired file

### ISSUE THREAD

**Issue by kam193** [CybercentreCanada/assemblyline#212]
**Describe the bug**
When I try to submit via UI a file that already exists in the malware archive, and it is old enough to have already been removed from the normal submissions, the UI fails with a timeout visible in the browser's networking tab. On the backend site, the `ui` container is freaking out with `ConflictError` exceptions and endless retries. In addition, it looks like interrupted submissions (e.g. because of restarting the container) aren't immediately removed from the quota - but I suspect they will be removed after some timeout.

**To Reproduce**
1. Have an archived submission that is after its TTL, and has already been removed from the normal submission index.
2. Go to the Submit page, open web developer tools to observe network traffic.
3. Try to upload the same file as in the submission from (1).
4. Wait until you see get an error in the UI or the traffic inspector.
5. Go to the logs of `ui` container. 
6. Observe endless retries with the errors like:
`{"@timestamp": "2024-03-28 23:28:30,167", "event": { "module": "assemblyline", "dataset": "assemblyline.datastore" }, "host": { "ip": "172.16.0.6", "hostname": "7209ae405eaa" }, "log": { "level": "INFO", "logger": "assemblyline.datastore" }, "process": { "pid": "7" }, "message": "Retrying save or freshen due to version conflict: ConflictError(409, 'version_conflict_engine_exception', '[xxx]: version conflict, required seqNo [13307], primary term [35]. but no document was found')"}`
8. Side note: due to the nature of gevent server workers, processing the request in `ui` container isn't interrupted even after being closed on the nginx side.

**Expected behavior**
I can upload a file even if it's already in the archive. The file is normally processed, and I eventually see additional information from the archive.

**Screenshots**
-

**Environment (please complete the following information if pertinent):**
 - Assemblyline Version: 4.5.0.7
 - Browser: Firefox

**Additional context**
I reproduced this with a few files, freshly expired (a day after TTL) as well as much older one (a few months after TTL). When I tried a file that is in the archive, but hasn't been expired yet, there was no problem.

**Comment by precise0** [comment]
I wanted to bump this issue, my deployment fully updated to the newest 4.5 stable channel is experiencing this issue as well. This is a pretty disruptive problem and I'd greatly appreciate if the maintainers could take some time to check this out.

**Comment by cccs-rs** [comment]
So if I understand the issue:

If you try and re-upload an archived submission that would've expired (based on the TTL), it raises an error from the API and fails?

**Comment by precise0** [comment]
I think the issue is caused once you submit a duplicate sample that is greater than the submission "Days to live" attribute and that sample has been archived.

**Comment by precise0** [comment]
> I think the issue is caused once you submit a duplicate sample that is greater than the submission "Days to live" attribute and that sample has been archived.

Sorry, let me be more clear in this wording: a duplicate sample that was first seen more than "Days to live" ago and has been archibed

**Comment by cccs-rs** [comment]
I will try to simulate this scenario as best as I can. I think I have a feeling what might be going on

If you prefer a more immediate messaging platform, you can join our Discord:
https://discord.gg/GUAy9wErNu

**Comment by cccs-rs** [comment]
@kam193 are you able to comment on whether or not this is still an issue for you?

Looking at the most recent code, assuming that if the file expires midway through the `save_or_freshen` call, then the version would've been replaced with a token that would create a new file rather than overwrite the version of the record. But the fact it was in a infinite loop is worrying so I'd like to understand the conditions as best as I can 😁

**Comment by kam193** [comment]
@cccs-rs I've just tried and on AL 4.5.0.48 I can still observe the problem :(

**Comment by cccs-rs** [comment]
The good news is we found the bug! 🤓

**Comment by cccs-rs** [comment]
This should be resolved in [4.5.0.51](https://github.com/CybercentreCanada/assemblyline/releases/tag/v4.5.0.stable51).
