### ISSUE TITLE
Missed .online static domain

### ISSUE THREAD

**Issue by kam193** [CybercentreCanada/assemblyline#214]
**Describe the bug**
In a code (attached) there is a gTLD `.online` domain, which wasn't recognized during a static analysis. I know that with gTLDs the static detection is especially hard, so it's also a question if - according to AssemblyLine goals - such a domain should be recognized in a standard analysis (not the deep scan).

**To Reproduce**
1. Upload the file [with-online.zip](https://github.com/CybercentreCanada/assemblyline/files/14965776/with-online.zip) (pass: zippy)
2. Wait for analysis.
3. Observe only `.py` found as a domain.
4. Open the file and find the `.online` domain. In quite an important place, though.

**Expected behavior**
The `.online` domain is found during static analysis.

**Screenshots**
-

**Environment (please complete the following information if pertinent):**
 - Assemblyline Version: 4.5.0.12, FrankenStrings 4.5.0.3

**Additional context**
-

**Comment by cccs-jh** [comment]
Hi, this is now fixed in FrankenStrings v4.5.0.6. It is intended to find domains with any valid TLD but frankenstrings was using an incomplete list of TLDs.
