### ISSUE TITLE
Suricata 4.5.0.7 seems to be broken

### ISSUE THREAD

**Issue by kam193** [CybercentreCanada/assemblyline#223]
**Describe the bug**
After upgrading Suricata service to v 4.5.0.7, every analyse of a PCAP file ends with:

```
  File "/var/lib/assemblyline/.local/lib/python3.11/site-packages/assemblyline_v4_service/common/base.py", line 181, in handle_task
    self.execute(request)
  File "/opt/al_service/suricata_/suricata_.py", line 267, in execute
    sha256, filename, extracted_file_path = file.values()
                                            ^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'values'
```

It appears to be totally independent whether the PCAP contains any files to extract or not.

My suspicion is that the commit https://github.com/CybercentreCanada/assemblyline-service-suricata/commit/df33beafb51211da04aaf0e2fb1123e4dcbb0bbe#diff-fbf3caf42b80c9be6f4d38504bf6689bf2b8c341a3bb00146cd875a6c123225dR261 on line 261 in `suricata_/suricata_.py` misses `.values()` that was there before :)

**To Reproduce**
1. Update Suricata to v 4.5.0.7
2. Analyse any file, e.g.  [_linux_EXTRACTED_tcpdump.pcap(2).zip](https://github.com/CybercentreCanada/assemblyline/files/15253723/_linux_EXTRACTED_tcpdump.pcap.2.zip) (password: zippy)

**Expected behavior**
Analyse is done and results are reported.

**Screenshots**
--

**Environment (please complete the following information if pertinent):**
 - Assemblyline Version: 4.5.0.21
 - Browser: [e.g. chrome, safari]

**Additional context**
-

**Comment by cccs-rs** [comment]
This should be resolved in the latest stable release.
