### ISSUE TITLE
FrankenStrings URL extraction seems to trim URLs on char 0, even when it's not a binary file

### ISSUE THREAD

**Issue by kam193** [CybercentreCanada/assemblyline#229]
**Describe the bug**
I've just observed that FrankenStrings started to trim URLs when they have a `0` inside. It looks like an attempt to fix extraction from binaries where URLs often weren't properly trimmed, but applied to text files results in too early trimming.

**To Reproduce**
1. Upload a file with an URL like `https://some.doma.in/pathwith0butnotended`, a real example: [utils.py.zip](https://github.com/CybercentreCanada/assemblyline/files/15461578/utils.py.zip) (pass: `zippy`, it contains a Discord webhook)
2. Wait on results.
3. See the URL extracted as `https://some.doma.in/pathwith`

**Expected behavior**
The full URL is extracted.

**Screenshots**
![obraz](https://github.com/CybercentreCanada/assemblyline/assets/8472271/19df28d5-91f2-4118-857a-ac807be218ca)

**Environment (please complete the following information if pertinent):**
 - Assemblyline Version: 4.5.0.26
 - FrankenStrings 4.5.0.6

**Additional context**

**Comment by cccs-jh** [comment]
You are exactly right, this is a false positive from a recently implemented pascal string check. I'll change it so it only runs on data files.

**Comment by cccs-rs** [comment]
This should be resolved in version [1.3.5 of the multidecoder package](https://pypi.org/project/multidecoder/1.3.5/) and in the latest stable release of Frankenstrings.
