### ISSUE TITLE
YARA service cannot parse rules with negative integers in metadata

### ISSUE THREAD

**Issue by kam193** [CybercentreCanada/assemblyline#231]
**Describe the bug**
If a rule contains a metadata with a value of a negative integer, the underlying yara parser cannot parse it and throws an error, effectively excluding the whole source from usage. 

**To Reproduce**
1. Let's use the following rule as an example: https://gist.githubusercontent.com/kam193/927de115443820443bd1024f8c6aecef/raw/20ef7466ef7c3316f8705afcaea29f271a2b9d28/example.yar
3. Add the rule as source to the YARA service.
4. Observe YARA update logs
5. See error like `Unknown text - for token of type HYPHEN on line 37`, logs:
```
{"@timestamp": "2024-05-31 09:37:14,180", "event": { "module": "assemblyline", "dataset": "assemblyline.updater.yara" }, "host": { "ip": "172.16.48.18", "hostname": "e5ee963a9412" }, "log": { "level": "INFO", "logger": "assemblyline.updater.yara" }, "process": { "pid": "1" }, "message": "Found new yara rule files to process for example_hypen!"}
{"@timestamp": "2024-05-31 09:37:14,181", "event": { "module": "assemblyline", "dataset": "assemblyline.updater.yara" }, "host": { "ip": "172.16.48.18", "hostname": "e5ee963a9412" }, "log": { "level": "INFO", "logger": "assemblyline.updater.yara" }, "process": { "pid": "1" }, "message": "Processing file: /tmp/tmpafitmp_x/example.yar"}
{"@timestamp": "2024-05-31 09:37:14,210", "event": { "module": "assemblyline", "dataset": "assemblyline.updater.yara" }, "host": { "ip": "172.16.48.18", "hostname": "e5ee963a9412" }, "log": { "level": "ERROR", "logger": "assemblyline.updater.yara" }, "process": { "pid": "1" }, "message": "Problem parsing /tmp/tmpafitmp_x/example.yar: Unknown text - for token of type HYPHEN on line 37"}
{"@timestamp": "2024-05-31 09:37:14,236", "event": { "module": "assemblyline", "dataset": "assemblyline.updater.yara" }, "host": { "ip": "172.16.48.18", "hostname": "e5ee963a9412" }, "log": { "level": "INFO", "logger": "assemblyline.updater.yara" }, "process": { "pid": "1" }, "message": "Importing file: /tmp/tmpocshjeg9example_hypen"}
{"@timestamp": "2024-05-31 09:37:14,262", "event": { "module": "assemblyline", "dataset": "assemblyline.updater.yara" }, "host": { "ip": "172.16.48.18", "hostname": "e5ee963a9412" }, "log": { "level": "INFO", "logger": "assemblyline.updater.yara" }, "process": { "pid": "1" }, "message": "There are no signatures for example_hypen, skipping..."}
```
6. Confirm looking for imported signatures that there was nothing imported - a useful step because UI presents the upgrade as successful

**Expected behavior**
Rules are imported.

**Screenshots**
A "succesful" result of loading rules (here with the whole set, so more than a one rules with an issue), although nothing was imported. The updater is in kind of loop trying to download updates, but presents a positive result when beinig in progress of refreshing other sources after the first try.
![obraz](https://github.com/CybercentreCanada/assemblyline/assets/8472271/836af67d-e2f0-4fe5-9cae-7c8159c42484)

**Environment (please complete the following information if pertinent):**
 - Assemblyline Version: 4.5.0.26
 - YARA service `4.5.0.7`

**Additional context**
The issue clearly comes from the underlying `plyara` library which does not parse negative values - you can reproduce it by calling the Plyara parser directly on the example rule. I haven't found any specification saying that it's an incorrect syntax - maybe you know something that would say it's an issue with the rule set? I'm trying to integrate the extended ruleset from Yara forge: https://github.com/YARAHQ/yara-forge

**Comment by cccs-rs** [comment]
Indeed the issue is with the underlying `plyara` package, I assume because of how the lexer is written to parse metadata.

A way I can workaround the issue is to manipulate the rule string to quote negative (presumably integer) values and then going through parsing as normal, then unquote the values so they're in their original form when re-compiling the rule.

**Comment by cccs-rs** [comment]
In the meantime until the PR gets approved, I can switch the service to use my fork of the `plyara` package with the fix to lexer's parsing logic:
https://github.com/cccs-rs/plyara/commit/4b6dd15810a7e92f1fa30dd2b0437d5cc3726ee8

**Comment by kam193** [comment]
Thanks for the fix! As a workaround, I currently just remove affected lines as the problem occurs only in metadata entries that aren't necessary to me

**Comment by cccs-rs** [comment]
Should be patched in the latest [stable release](https://github.com/CybercentreCanada/assemblyline-service-yara/releases/tag/v4.5.0.stable10) of the YARA and TagCheck service.
