### ISSUE TITLE
Error: 504 Gateway-Timeout when all containers are up and healthy.

### ISSUE THREAD

**Issue by Al3xTh3Gr3at** [CybercentreCanada/assemblyline#234]
**Describe the bug**
When starting ALv4 dev setup, the gui doesn't bring up the login page and has an error of "Error: 504 Gateway-timeout

**To Reproduce**
1. Go To /git/alv4/assemblyline-base/dev/depends
2. $docker-compose -f docker-compose-minimal.yml up -d --wait
3. Go to /git/alv4/assemblyline-base/dev/core
4. $docker-compose -f docker-compose.yml up -d --wait
5. Wait until all containers are started and healthy. 
6. Open your browser and navigate to https://localhost
7. No local login option with Error: API Server unreachable, we will auto-reconnect once the server is back online...

**Expected behavior**
https://localhost brings up the AssemblyLine GUI. 

**Screenshots**

**Workaround**
1. run $docker inspect depends-nginx-1 and find the Gateway and IPAddress
2. <img width="163" alt="dockerinspectnginx" src="https://github.com/CybercentreCanada/assemblyline/assets/165163865/95f559f7-dae4-4f05-9a84-c257651c45c8">
3.Go To /git/alv4/assemblyline-base/dev/depends
4. nano docker-compose-minimal.yml (scroll to the bottom)
5. Make sure the IPs are in the same subnet.  
<img width="218" alt="nginx-info" src="https://github.com/CybercentreCanada/assemblyline/assets/165163865/c76f08ce-e869-47d3-8fd0-64f2e52569a4">

**Environment (please complete the following information if pertinent):**
 - Assemblyline Version: 4.5.0.29
 - Browser: FireFox

**Comment by cccs-rs** [comment]
Is this with using the latest commit from `assemblyline-base`? Mostly because you reference 4.3.1.x as the version and we're currently on 4.5.0.x so I wonder if it's a bug that's since been patched.

**Comment by kam193** [comment]
Have you tried to restart Nginx container? I have an issue that Nginx is sometimes failing to find containers that weren't available when it was starting. I just restart Nginx container to fix it.

**Comment by Al3xTh3Gr3at** [comment]
Apologies, it is from the latest version..

**Comment by cccs-rs** [comment]
Running this myself, I haven't encountered any issues and in my case the gateway gets set to `172.24.0.1` which doesn't match the IP that's set for NGINX by default (`172.17.0.1`) but the default matches the IP shown for `ip addr show docker0`.

Perhaps in your system, the IP address for Docker is different and you may need to set that instead in the docker-compose.yml?

**Comment by Al3xTh3Gr3at** [comment]
Yup, setting it in the yml file fixed the issue!

Thank you
