### ISSUE TITLE
Add the possiblity to specify core-only secrets in the helm chart

### ISSUE THREAD

**Issue by sbjzn** [CybercentreCanada/assemblyline#236]
**Is your feature request related to a problem? Please describe.**
I am currently using the coreEnvs to fetch and set OAuth secrets, however these secrets are also exposed to privileged services.

**Describe the solution you'd like**
A way to specify environment variables that are only applied to the core components, and no services at all.

**Describe alternatives you've considered**
I can't find any other way to do this other than modifying the helm chart.

**Additional context**
This comment in values.yaml is misleading, the wording should probably be changed to mention that the variables are exposed to privileged services.

```text
# Extra environment variables, mounts, and volumes shared by all core containers
# Any environment variables set here can be used in the value strings of any
# field under the configuration.* block. This is the proper way to pass a secret
# to the assemblyline core components. These values won't be passed to analysis
# services.
```

**Comment by cccs-rs** [comment]
This should be patched in [4.5.0.37](https://github.com/CybercentreCanada/assemblyline/releases/tag/v4.5.0.stable37).
