### ISSUE TITLE
Python code identified as text/plain

### ISSUE THREAD

**Issue by kam193** [CybercentreCanada/assemblyline#238]
**Describe the bug**
The attached code was identified as text/plain instead of python code. As it has quite a few typical patterns (`import requests`, defining a function) I think it may be worth adjusting the file identification.

**To Reproduce**
1. Upload the file  [main.py.zip](https://github.com/user-attachments/files/16033814/main.py.zip) (pass: zippy)
2. Look at the file identification.

**Expected behavior**
File should be identified as code/python

**Screenshots**

**Environment (please complete the following information if pertinent):**
 - Assemblyline Version: 4.5.0.32
 - Extract service: 4.5.0.20 (file was extracted, and the service is in privileged mode)

**Additional context**

**Comment by gdesmar** [comment]
This previous pull request should cover this sample and a few more, but it may not be good enough for the next one. Feel free to open an issue any time you find a file that is missed.

If you have a list of standard library functions that are often used by malicious python malware, I would be very interested. I feel like it may be a cat and mouse game with the current yara rule setup, as it could easily be bypassed by doing an `import socket as so`, and even flagging on `import socket` could be bypassed with `import math, socket as so`. 

It may end up being needed, and doable with a regex, but we'd need to be wary of false positive for python identification.

Regarding the function definition, we are flagging it, but we are currently setup to require two strong indicators (or one executor from CybercentreCanada/assemblyline/issues/222).

**Comment by kam193** [comment]
Thank you for extending rules!

Yeah, I'm aware this is not an easy thing to identify everything. I think the current approach, libmagic + rules, is probably the best we have at the moment. I saw you were looking at Google's magika, what can be an interesting extension, but I do not know any better method, so I share examples when I think it could be important to properly mark :)

The idea of functions most often used by malware is quite interesting. I don't have any at the moment, although I started experimenting with Semgrep rules (what overcomes some troubles caused by the syntax flexibility, but requires knowing the language in advance) - so I may collect one at some point, then I'll share it. One interesting source, but I've already shared it, are rules from the [GuardDog repository](https://github.com/DataDog/guarddog/tree/main/guarddog/analyzer/sourcecode). But I think the current Yara rules are already quite strong.

**Comment by kam193** [comment]
Hey, I've run into another (not malicious) file with missed identification:
[load_test.py.zip](https://github.com/user-attachments/files/16120283/load_test.py.zip) (pass: zippy). But it has a very string Python indicators, so it would be nice to include in the identification rules:
- `import asyncio`
- `asyncio.run`
- `import httpx`
- `httpx.AsyncClient`

`httpx` is the new `requests` with HTTP/2 support, so I expect broader usage over time in the malware.

**Comment by gdesmar** [comment]
Added a couple httpx and asyncio functions to the previous PR that wasn't merged yet, and merged it. They should all be identified correctly with the next release.
Thank you!
