### ISSUE TITLE
Tag type text is cut-off when creating new badlist item

### ISSUE THREAD

**Issue by jasper-vdhoven** [CybercentreCanada/assemblyline#240]
**Describe the bug**
When creating a new badlist item from the "Manage" menu item the tag description text is cut-off prior to the end of the tag text itself; making it hard to read which one you're currently selecting without explicitly typing it out.

**To Reproduce**
1. Go to Manage -> Badlist
2. Click on 'add_badlist' (green plus icon in the top right)
3. Select 'tag' as badlist type
4. Click on the tag dropdown and the tag text should be cutoff before the end of the tag name itself

**Expected behavior**
When selecting the dropdown I expected to be able to read the tag text in its entirety. This because for some tags there are two variants (f.e. network.static.domain and network.dynamic.domain) and one might only want to create the badlist for one of them.

**Screenshots**
Below is a screenshot which demonstrates the cut-off tag text:
<img width="1089" alt="image" src="https://github.com/CybercentreCanada/assemblyline/assets/22278716/3dae3538-01a8-4b08-bff1-c3cda78949a7">
<img width="1089" alt="image" src="https://github.com/CybercentreCanada/assemblyline/assets/22278716/675d52ed-265b-4311-9204-cd07c120c077">

**Environment (please complete the following information if pertinent):**
 - Assemblyline Version: 4.5.0.33
 - Browser: Arc 1.49.1, Microsoft Edge 126.0.2592.87, Firefox 127.0.2

**Comment by cccs-rs** [comment]
This should be resolved in the [4.5.0.61](https://github.com/CybercentreCanada/assemblyline/releases/tag/v4.5.0.stable61) release.
