### ISSUE TITLE
Strack traces on are given to the user even when debugging is disabled

### ISSUE THREAD

**Issue by cyberspacecadet** [CybercentreCanada/assemblyline#246]
**Describe the bug**
Even when debugging has been disabled in the UI, stack traces are given to the user. [This goes against OWASP's error handling guidance:](https://owasp.org/www-community/Improper_Error_Handling)

> Improper handling of errors can introduce a variety of security problems for a web site. The most common problem is when detailed internal error messages such as stack traces, database dumps, and error codes are displayed to the user (hacker).

**To Reproduce**
1. Ensure the debugging flag is not set in the UI config
3. Cause an exception:
```
curl -X POST https://al4.beta.bytebox.security.aws.dev/api/v4/user/settings/al4user/ -H 'x-apikey: AL4:USER' -H "x-user: al4user" -H "Content-Type: application/json" --data '{"services": "THIS_STRING_CAUSES_AN_UNHANDLED_EXCEPTION", "default_zip_password": "zippy"}'
```

**Expected behavior**
When debugging is disabled, stack traces should be hidden from the user.

**Screenshots**
Example output:
```
{"api_error_message":"\n  File \"/var/lib/assemblyline/.local/lib/python3.11/site-packages/flask/app.py\", line 2190, in wsgi_app\n    response = self.full_dispatch_request()\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/lib/assemblyline/.local/lib/python3.11/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/lib/assemblyline/.local/lib/python3.11/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n    rv = self.dispatch_request()\n         ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/lib/assemblyline/.local/lib/python3.11/site-packages/flask/app.py\", line 1469, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/lib/assemblyline/.local/lib/python3.11/site-packages/assemblyline_ui/api/base.py\", line 235, in base\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/lib/assemblyline/.local/lib/python3.11/site-packages/assemblyline_ui/api/v4/user.py\", line 949, in set_user_settings\n    if save_user_settings(username, data):\n       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/lib/assemblyline/.local/lib/python3.11/site-packages/assemblyline_ui/helper/user.py\", line 300, in save_user_settings\n    data[\"services\"] = {'selected': simplify_services(data[\"services\"])}\n                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/lib/assemblyline/.local/lib/python3.11/site-packages/assemblyline_ui/helper/service.py\", line 56, in simplify_services\n    if item[\"selected\"]:\n       ~~~~^^^^^^^^^^^^\nTypeError: string indices must be integers, not 'str'","api_response":"","api_server_version":"4.5.0.40","api_status_code":500}
```

**Environment (please complete the following information if pertinent):**
 - Assemblyline Version: 4.5.0.stable40
 - Curl

**Additional context**
This was spoken to here in Discord: https://discord.com/channels/908084610158714900/909824247273246750/1260232770697826438

This fix has been working internally, along with a little more logic to handle exceptions to result in a 400 response:
https://github.com/CybercentreCanada/assemblyline-ui/pull/1016

**Comment by cccs-rs** [comment]
This should be resolved in the [4.5.0.41](https://github.com/CybercentreCanada/assemblyline/releases/tag/v4.5.0.stable41) release of Assemblyline
