### ISSUE TITLE
SAML Authentication Support

### ISSUE THREAD

**Issue by eljeffeg** [CybercentreCanada/assemblyline#25]
Would like to request SAML Authentication support.  I'm currently using LDAP in our dev, but production will need to be able to use SAML to authenticate users.  Wanted to try and get this on the roadmap.  Thanks

**Comment by cccs-rs** [comment]
This was patched in the [4.5.0.27](https://github.com/CybercentreCanada/assemblyline/releases/tag/v4.5.0.stable27) release.
