### ISSUE TITLE
 assemblyline-service-safelist bug in update_server.py

### ISSUE THREAD

**Issue by BolidCyber** [CybercentreCanada/assemblyline#256]
**Describe the bug**
 in assemblyline-service-safelist project version 4.5.0.stable13, the method declaration **import_update** have three parameters but the call have four parameters

**To Reproduce**
1. Go to assemblyline-service-safelist project with tag V4.5.0.stable13
2. Open file update_server.py
3. line 196  `def import_update(self, file_path, source_name: str, default_classification=None):`
4. line 330 ` self.import_update(file, self.client, source_name, default_classification)`

**Expected behavior**
No errors during NSRL updates

**Screenshots**
NA

**Environment (please complete the following information if pertinent):**
 - assemblyline-service-safelist Version: [4.5.0stable13]

**Additional context**
NA

**Comment by cccs-rs** [comment]
Should be patched in the [latest release of the service](https://github.com/CybercentreCanada/assemblyline-service-safelist/releases/tag/v4.5.0.stable14). Thanks for raising the issue to us!
