### ISSUE TITLE
Ability to host Signatures locally

### ISSUE THREAD

**Issue by zn-lab** [CybercentreCanada/assemblyline#263]
**Is your feature request related to a problem? Please describe.**
Currently signatures must be ingested from external source to AL4.
This might create an issue if you had not setup a publicly facing git repo.

**Describe the solution you'd like**
Ability to host signatures locally on the platform

**Describe alternatives you've considered**

**Additional context**
For example: Yara signatures we had to setup a dedicated git repo as an individual which is bad for RBAC.
@cccs-rs

**Comment by cccs-rs** [comment]
This should be resolved in the [4.5.0.66](https://github.com/CybercentreCanada/assemblyline/releases/tag/v4.5.0.stable66) release and all services built under this release.
