### ISSUE TITLE
Default TagCheck rules

### ISSUE THREAD

**Issue by kam193** [CybercentreCanada/assemblyline#265]
**Describe the bug**
I've just recognized that the default TagCheck rules config points to the file in Azure, but there is also a file in Github that looks to be newer? extended?

So: question/bug: are both files relevant, or do you suggest using only one of them?

**To Reproduce**
1. Look at the file provided in service manifest: https://github.com/CybercentreCanada/assemblyline-service-yara/blob/master/tagcheck/service_manifest.yml
2. Compare with https://github.com/CybercentreCanada/assemblyline-service-yara/blob/master/tagcheck/rules/tagcheck.rules

**Expected behavior**

**Screenshots**

**Environment (please complete the following information if pertinent):**
 - Assemblyline Version: TagCheck 4.5.0.17

**Additional context**

**Comment by cccs-rs** [comment]
Looks like the rules we store in Github are more up-to-date than the ones in Azure, I'll update the manifest to reflect that preference.

**Comment by cccs-rs** [comment]
This should be resolved in the latest release of the service.
