### ISSUE TITLE
File name and type in TagCheck rules (& YARA rules) to be used for matching

### ISSUE THREAD

**Issue by cccs-rs** [CybercentreCanada/assemblyline#269]
### Discussed in https://github.com/CybercentreCanada/assemblyline/discussions/264

<div type='discussions-op-text'>

<sup>Originally posted by **kam193** September 19, 2024</sup>
I use TagCheck service to mark some indicators - and this is a great feature! However, I could potentially lower the number of false positives if I could filter out given file names and types (in my use case, the file name often matters more than type). 

And here comes my question: is it already supported by TagCheck? I'm not sure if I don't miss something: generally, TagCheck seems to get only data from `Tagging` ODM models ([tagcheck/tagcheck.py#L9](https://github.com/CybercentreCanada/assemblyline-service-yara/blob/060a5ddb514d2dd16e9a7220df80d71b775098af/tagcheck/tagcheck.py#L9)), which, I think, do not usually contain those data. I see however mentioning e.g. `file_type` in the default `YARA_EXTERNALS` ([yara_/helper.py#L13](https://github.com/CybercentreCanada/assemblyline-service-yara/blob/060a5ddb514d2dd16e9a7220df80d71b775098af/yara_/helper.py#L13)), but it looks to be used only in the default Yara service ([yara_/yara_.py#L57](https://github.com/CybercentreCanada/assemblyline-service-yara/blob/060a5ddb514d2dd16e9a7220df80d71b775098af/yara_/yara_.py#L57) - and BTW, won't they get the `al_al_` prefix in the [yara_/yara_.py#L64](https://github.com/CybercentreCanada/assemblyline-service-yara/blob/060a5ddb514d2dd16e9a7220df80d71b775098af/yara_/yara_.py#L64)?).

So, I'm unsure if I didn't miss anything. Is the case of matching name and/or type of the submitted file already supported? 
</div>

**Comment by kam193** [comment]
@cccs-rs I've created a PR that handles that as well as fixes using externals - there were a few other issues in handling them as well. Would you have a second to take a look and test on your end?

**Comment by kam193** [comment]
Thank you!

**Comment by cccs-rs** [comment]
No no, thank you! 🥰
