### ISSUE TITLE
Cannot disable badlist tag

### ISSUE THREAD

**Issue by kam193** [CybercentreCanada/assemblyline#273]
**Describe the bug**
I've found out, I'm no longer able to disable a tag in badlist, at least tags imported from a source. It looks like the request sent is empty, but the server requires body.

**To Reproduce**
1. Have some badlisted tags, in my case: domains from threatview.io_Domain_Blocklist
2. Find the tag in Badlist view and open details.
3. Click on the disable button and confirm
4. See error: 
![image](https://github.com/user-attachments/assets/3eda882b-dc07-4e57-9fa8-cc426de04c6e)

When verifying with the developer tools, I see a PUT request to `https://[...]/api/v4/badlist/enable/be26b4391a2bb0f6eb2cbb5c17cb53f689f8303a605bd2b13dc71b2b3a97e197/` with the `application/json` content type, but no body at all. The answer: 
![image](https://github.com/user-attachments/assets/20219570-5457-4515-b510-15d2b9be446a)

**Expected behavior**
Badlist tag should be disabled.

**Screenshots**

**Environment (please complete the following information if pertinent):**
 - Assemblyline Version: 4.5.0.51
 - Browser: Firefox

**Additional context**
I can still remove the tag.

**Comment by cccs-rs** [comment]
I believe this bug is related to no payload being set (namely a boolean), which doesn't seem to be the case in the release. @kam193 can you confirm if this is still an issue?

**Comment by kam193** [comment]
I've just tested and indeed, the issue was solved. Thanks!
