### ISSUE TITLE
Priority difference between API and UI

### ISSUE THREAD

**Issue by kh4rdur** [CybercentreCanada/assemblyline#277]
When builing some automatic ingestion flows we noticed the Priority values didnt get picked up correctly. We tested setting the priority to 100 on ingestion through the API, it still shows as High in the UI; altho when uploading a file by the UI, we notice a different value for High medium and Low.

- upload a file with the ingestion scripts and change the Priority value between 100 and 1000 
- upload a file in the UI and set the value to low medium or hight and check the value.

**Expected behavior**
We would expect the values to be more of the same; or see the documentation to be explaining the differences.

**Screenshots**
Screenshots can be find within the Troubleshooting chat on Discord; 
https://discord.com/channels/908084610158714900/908717528082173983/1296016572015575122

**Environment (please complete the following information if pertinent):**
 - Assemblyline Version: Latest Version
 - Browser: Chrome

**Additional context**
As per request this ticket was created. @cccs-rs replied to the question and adviced to create a ticket for this.
(https://discord.com/channels/908084610158714900/908717528082173983/1296087138458140732)

**Comment by cccs-rs** [comment]
This should be patched in the [4.5.0.62](https://github.com/CybercentreCanada/assemblyline/releases/tag/v4.5.0.stable62) release.
