### ISSUE TITLE
Enhancement: Services Loaded

### ISSUE THREAD

**Issue by eljeffeg** [CybercentreCanada/assemblyline#28]
It would be nice if you could add a column for Internal / External services.  That would be great to see at a glance since it involves less network isolation and sending info about your malware to others (even if it's just a hash).

**Comment by cccs-sgaron** [comment]
Fixed by: 
https://github.com/CybercentreCanada/assemblyline-ui/pull/647
https://github.com/CybercentreCanada/assemblyline-ui-frontend/pull/613

**Comment by cccs-rs** [comment]
Fixed in [Release 4.4.0.21](https://github.com/CybercentreCanada/assemblyline/releases/tag/v4.4.0.stable21)
