### ISSUE TITLE
How can a service determine the classification of the request/task?

### ISSUE THREAD

**Issue by lfreijo** [CybercentreCanada/assemblyline#283]
I'm writing a small service to connect assemblyline to an external api. I would like to be able to determine the classification of the submission to propagate that to the external service. This is a connector between two systems and the other system can also be accessed by users so I need to keep the classification in sync. 

The only object that a service has available to it (as far as I can tell) is the ServiceRequest passed into execute(). This has the task with min_classification and service_default_result_classification. Neither of those match the classification I select when submitting a file. I can see that the API does support querying for the submission and returning the classification that way, but that seems like a clunky solution from within the service.

Is there any other way a service can access the request's classification?

**Comment by cccs-rs** [comment]
The task's `min_classification` should match the classification of the submission:
https://github.com/CybercentreCanada/assemblyline-core/blob/f6ecd48e1b47306df7f409abd0ec205a9e0d5961/assemblyline_core/dispatching/dispatcher.py#L783C25-L783C43

**Comment by cccs-rs** [comment]
The classification you see in the UI might differ from the original submitted classification depending on the content displayed (ie. heuristics from a service at a much higher classification)

**Comment by lfreijo** [comment]
Thanks for the fast response! That is what I initially thought, but it does not seem to be matching. Any classification I select always shows as "TLP:C". Perhaps there is something wrong with my classification yaml? The final report and submission appear to be marked correctly from the UI and API just not within the service.

**Comment by cccs-rs** [comment]
Hmm... were they changes to the classification.yaml? I wonder if one part of the system or another doesn't know how to interpret a new marking and it's just defaulting to `TLP:C`.

**Comment by cccs-rs** [comment]
Hmm... assuming the same classification file is mounted in the service on `/etc/assemblyline/classfication.yml`, it should be able to interpret the classification strings that the dispatcher is sending. Unless there's a bug in the dispatcher that's sending the wrong classification in the task to the service.

Would you be able to test this?

**Comment by lfreijo** [comment]
Ok. Thanks to your tip I was able to get it to work. Manually copying the config to /etc/assemblyline/classfication.yml in the service container made the values work as expected! So we are using a docker install right now to get our feet wet. I am guessing this is not an issue if we move to k8s. 
Is there a way to get the docker install to automatically mount this and any other config we need?

**Comment by cccs-rs** [comment]
Judging by the code, it looks like you just have to tell Scaler via env where to find the classification.yml on the host and it should share it to the services it manages:

https://github.com/CybercentreCanada/assemblyline-core/blob/f6ecd48e1b47306df7f409abd0ec205a9e0d5961/assemblyline_core/scaler/scaler_server.py#L67

**Comment by lfreijo** [comment]
Awesome. Thank you for your help!
