### ISSUE TITLE
Enhance Archive Extractions

### ISSUE THREAD

**Issue by malvidin** [CybercentreCanada/assemblyline#285]
The `extract` service uses 7zip to extract files from archives. In cases of some malformed ZIP archives, this option extracts different files than Windows Explorer and WinRAR. I agree with the 7zip developers that this is not bug in 7zip.

https://perception-point.io/blog/evasive-concatenated-zip-trojan-targets-windows-users/

I expect Assemblyline to identify this as a suspicious Heuristic and extract files from one or more archives appended after the first central directory. The files extracted from archives appended to the initial archive should be correlated in some way to the original file, possibly through an "appended archive" that is extracted and resubmitted without the header.

```mermaid
flowchart TD
    ma[Submitted ZIP Archive
    ZIP 1 + ZIP 2 + ZIP 3]
    ma --extract--> aa1(ZIP 1
    file10
    file11)
    ma --subfile--> a2[ZIP 2]
    a2 --extract--> aa2(ZIP 2
    file20
    file21)
    ma --subfile--> a3[ZIP 3]
    a3 --subfile--> aa3(ZIP 3
    file30
    file31)

```

Users can use YARA to identify file entries after the central directory, but there is not an easy way to resubmit a file without the first ZIP archive. The user can manually compare the result from `extract` which shows the first archive's metadata, and the result from `characterize` which shows the last archive's metadata, but that does not analyze the second archive's contents.

This is the example ZIP archive (base64 encoded) as described in the blog post.
```
UEsDBAoAAAAAAL2Aa1lvuF2AGQAAABkAAAAJABwAZmlyc3QudHh0VVQJAANmKzJnZisyZ3V4CwAB
BLgj8wsEQQ/zC3RoaXMgaXMgYSBoYXJtbGVzcyBmaWxlIQpQSwECHgMKAAAAAAC9gGtZb7hdgBkA
AAAZAAAACQAYAAAAAAABAAAAgIEAAAAAZmlyc3QudHh0VVQFAANmKzJndXgLAAEEuCPzCwRBD/ML
UEsFBgAAAAABAAEATwAAAFwAAAAAAFBLAwQUAAAACADDgGtZ05tNZBwAAAAdAAAACgAcAHNlY29u
ZC50eHRVVAkAA20rMmdtKzJndXgLAAEEuCPzCwRBD/MLC8nILFYAokSFstSiSoXi5EQgmZuYU55Y
lMoFAFBLAQIeAxQAAAAIAMOAa1nTm01kHAAAAB0AAAAKABgAAAAAAAEAAACAgQAAAABzZWNvbmQu
dHh0VVQFAANtKzJndXgLAAEEuCPzCwRBD/MLUEsFBgAAAAABAAEAUAAAAGAAAAAAAA==
```

**Comment by gdesmar** [comment]
I built two new versions of Extract, v4.5.0.stable49 and v4.5.0.dev51, which should give you the desired behaviour with zip files that contain appended data at the end. Your example file now gets both text files extracted. Thank you for the issue!
