### ISSUE TITLE
processing for NSIS installers

### ISSUE THREAD

**Issue by cccs-rs** [CybercentreCanada/assemblyline#34]
Discord: https://discord.com/channels/908084610158714900/908717441771794472/1019296110239567963

_Does Extract (or any other service) have any processing for NSIS installers? Was hoping to extract [NSIS].nsi if it's available in the exe file_

Possible decompilers: https://nsis.sourceforge.io/Can_I_decompile_an_existing_installer%3F
Magic for identify:  `Nullsoft Installer self-extracting archive`

**Comment by cccs-sgaron** [comment]
Was this fixed ?

**Comment by gdesmar** [comment]
The nsidis project was used as a base into my fork of the nrs project. It is very incomplete but it is a good starting point to get the main elements decompiled. Any request for improvement on the current decompilation should open a new ticket with a specific element that is wanted, as there are probably hundreds and it would take too long to handle them all.
