### ISSUE TITLE
Bug: extract service will enter CrashingOnLoop until Privileged mode is disabled

### ISSUE THREAD

**Issue by C-Oliver** [CybercentreCanada/assemblyline#40]
**Describe the bug**
We noticed that the extract service will enter into crashing on loop if privileged mode is enabled. This seems to be related to heartbeat, as we can see a heartbeat error when you describe the pod.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Services tab
2. Click on Extract, and make sure Privileged mode is enabled
3. Save settings and wait for new pod to come up, you'll notice this pod will never come up unless you disable privileged mode

**Expected behaviour**
Should work in both privileged and normal mode.

**Screenshots**
Can replicate if required

**Environment (please complete the following information if pertinent):**
 - Assemblyline Version: 4.3.1.16
 - Browser: Edge

**Additional context**
Happy to provide any additional information as needed.

**Comment by cccs-rs** [comment]
Some questions (assuming Kubernetes deployment):

- Is the issue exclusive to Extract running in privileged or any service?
- `"heartbeat error when you describe the pod"`: sounds related to the probes, is the cluster particularly busy at the time when this happens?
- TLS enabled?
- `"you'll notice this pod will never come up unless you disable privileged mode"`: is Scaler not scaling up the deployments or is the pod not reaching a ready state?

**Comment by C-Oliver** [comment]
> Some questions (assuming Kubernetes deployment):
> 
> * Is the issue exclusive to Extract running in privileged or any service?

1. Yes just the extract service

> * `"heartbeat error when you describe the pod"`: sounds related to the probes, is the cluster particularly busy at the time when this happens?

2. No, this is the dev environment no processing happening at this time.

> * TLS enabled?

3. Not on Dev no

> * `"you'll notice this pod will never come up unless you disable privileged mode"`: is Scaler not scaling up the deployments or is the pod not reaching a ready state?

4. The pod never reaches a ready state, describing pods shows "healthz" failed

**Comment by cccs-rs** [comment]
Would you be able to provide:

- Service version
- Resource allocation for the service (requests/limits for CPU, RAM)

If Extract is the only privileged service that's probe is failing (but others are working), I'd be curious as to why. Perhaps it's a broken service build or the config.yaml isn't being shared properly to that service and needs to be re-created by Scaler.

**Comment by cccs-rs** [comment]
Any updates regarding this issue?

**Comment by C-Oliver** [comment]
<img width="707" alt="image" src="https://user-images.githubusercontent.com/4215842/226571425-8b7f93ce-95d2-4672-a449-76f16088d710.png">

<img width="704" alt="image" src="https://user-images.githubusercontent.com/4215842/226571514-2b2f599d-0cfb-42e1-a26b-c0d1eaa76240.png">

Issue is present on both dev and prod, even on latest version. Pods have been restarted multiple times, and issue is only on Extract, other services are set to privileged and work fine.

**Comment by C-Oliver** [comment]
Actually I see the same issue on the new Ancestry service. VirusTotal Service works fine.

**Comment by cccs-rs** [comment]
Any updates on this?

**Comment by cccs-rs** [comment]
Going to close the issue for now. If this is still an issue, feel free to re-open with more information😀
