### ISSUE TITLE
FIPS mode fails to import Python 3.9 crypt

### ISSUE THREAD

**Issue by malvidin** [CybercentreCanada/assemblyline#43]
**Describe the bug**
If kernel FIPS mode is enabled, the UI and services fails because they cannot import crypt.

**To Reproduce**
1. Enable kernel FIPS mode
2. Attempt to start development environment with Docker Compose
3. UI fails to start and logs show a crypt import error

**Expected behavior**
Import crypt statement succeeds

**Additional context**
This issue is fixed in Python 3.10 and higher.
https://github.com/python/cpython/commit/2fa03b1b0708d5d74630c351ec9abd2aac7550da
https://github.com/python/cpython/issues/95231

**Comment by cccs-kevin** [comment]
PR on AL base: https://github.com/CybercentreCanada/assemblyline-base/pull/1097

**Comment by malvidin** [comment]
The UI may use a different Dockerfile, so fixing the assemblyline-base may not fix all of the images.

**Comment by cccs-rs** [comment]
This PR should resolve it since the change needs to be in the root-image we use to build all released images from:
https://github.com/CybercentreCanada/assemblyline/pull/48
