### ISSUE TITLE
Feature Request: Submissions should allow tagging

### ISSUE THREAD

**Issue by C-Oliver** [CybercentreCanada/assemblyline#44]
**Is your feature request related to a problem? Please describe.**
Assemblyline should have the ability to add tags to a submissions, this can be used to tag campaigns, groups, and more.

**Describe the solution you'd like**
Each submission should have the ability to be tagged by the analyst, such that the list would appear somewhere along here:

<img width="907" alt="image" src="https://user-images.githubusercontent.com/4215842/223676784-2b358c91-f821-43bf-86a1-7253764998c7.png">

users should than be able to search based on these tags, and also query the API based on these tags.

These tags are not the IOC tags extracted from the submission, here tags refers to a free form text which would allow us add extra information to the submission.

One use case would be  tagging a submission as "production" this means that automation can pick the IOCs up from this submission and push them to production.

Another user case would be tagging a submission with a particular APT name, users can than query or search on these tags to find all the malware samples belonging to that APT, similar use case for campaigns.

There should not be a limit to how many tags a submission can have, or maybe controlled through values.yaml 

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by cccs-sgaron** [comment]
What you probably want to use here is the metadata section of the submission. In there, you can store any kind of information you would like about your submission and search that information at any time. The metadata will be displayed in the report, the submission detail and will be preserved in the alerts as well.

During your ingest/submit api call, just add:`metadata={"key": "value", "key2": "value2" ...}`

**Comment by C-Oliver** [comment]
This is good to know, thank  you! A UI element would also be beneficial as some of submissions are made manually, and tags will be added after the analysis is done on submission results. Sometimes users don't know if a submission belongs to an actor until its analysed. However, the above is good to know and we'll add it as an initial implementation.

**Comment by cccs-sgaron** [comment]
We usually don't let analyst modify submissions after the fact but when we rollout the malware archive feature, analysts will be able to label submission/files, add comments, etc... The malware archive will act more as a malware analysis plateform not just a malware triaging like AL is right now.
