### ISSUE TITLE
oauth flow sign-in flow bug

### ISSUE THREAD

**Issue by ed4wg** [CybercentreCanada/assemblyline#53]
**Describe the bug**

After updating from 4.3.0.stable62 to 4.3.1.stable23 user's are not able to sign-in to AL using oauth. The non-oauth sign-in flow still works as expected.

**To Reproduce**
The flow is: you get the initial sign-in page, you sign-in with your oauth provider, then it takes you back to AL where you hit sign in one more time. When you click the sign in button, it takes you to a page that says `There's definitely a 'bug' here!`  

The message on Chrome is: `Cannot read properties of undefined (reading 'toUpperCase').` 
The message on firefox is: `e[0] is undefined.`

**Environment (please complete the following information if pertinent):**
 - Assemblyline Version: 4.3.1.stable23

**Comment by cccs-sgaron** [comment]
This will be fixed by the following PR: https://github.com/CybercentreCanada/assemblyline-ui-frontend/pull/549
