### ISSUE TITLE
Minio does not support being backed by host FS anymore

### ISSUE THREAD

**Issue by LeanVel** [CybercentreCanada/assemblyline#57]
Since the release of [RELEASE.2022-10-29T06-21-33Z](https://github.com/minio/minio/releases/tag/RELEASE.2022-10-29T06-21-33Z) minio does not support being backed by the host file system. If an admin would chose to change the compose file to bind a host FS to the minio "/data", the following error is triggered when trying to run AL when the latest version of MINIO container is used.
` ERROR Unable to use the drive /data: Drive /data: found backend type fs, expected xl or xl-single`
[Documentation Reference](https://min.io/docs/minio/linux/operations/install-deploy-manage/migrate-fs-gateway.html)

As a workaround one could modify the compose file to use the last image that supports FS. Like this
`image: ${REGISTRY}minio/minio:RELEASE.2022-10-24T18-35-07Z`

It might be a good idea to add a note in the documentation and have a way to support host FS, specially since the filestore would usually run on a slower disk.

**Comment by cccs-rs** [comment]
Closing issue as this doesn't seem to be an issue with the latest version of MinIO that I'm currently running (RELEASE.2023-05-18T00-05-36Z).

If this is still a problem, feel free to reopen the issue.
