### ISSUE TITLE
EmlParser Header Filter Fails on MSG

### ISSUE THREAD

**Issue by malvidin** [CybercentreCanada/assemblyline#61]
The EmlParser does not perform case insensitive filtering of email headers for submissions with the type "document/office/email".

**To Reproduce**
1. Add "DKIM-Signature" to header_filter in the EmlParser service
2. Submit MSG file that contains a DKIM-Signature header
3. View EmlParser results in the submission
4. DKIM Signature is included in the Email Headers section for the EmlParser

**Expected behavior**
The header_filter should be consistent across submission file types

**Additional context**
The msg parser does not make case-insensitive comparisons
https://github.com/CybercentreCanada/assemblyline-service-emlparser/blob/d1035125f6222255c2e7846dd3d1ef214e1947f1/emlparser/emlparser.py#L63

The eml parser makes case-insensitive comparisons:
https://github.com/CybercentreCanada/assemblyline-service-emlparser/blob/d1035125f6222255c2e7846dd3d1ef214e1947f1/emlparser/emlparser.py#L412

**Comment by gdesmar** [comment]
Thank you for the report and sorry for the delay!
I'll go ahead and close this ticket, please feel free to reach out here or on discord if it is not working as expected!
