### ISSUE TITLE
Getting error from a file submission using assemblyline-client 4.5.0

### ISSUE THREAD

**Issue by robthew** [CybercentreCanada/assemblyline#63]
**Describe the bug**
Using the assemblyline-client, version 4.5.0 to submit a file for analysis, the client 'submit()'  is returning an error: "Error: __init__() missing 1 required positional argument: 'status_code'".

In the assemblyline-client code, the 'ClientError' class takes a 'status_code' as a required parameter, and I think whatever is throwing an exception is trying to instantiate a 'ClientError', but failing to supply a 'status_code'. So, instead of seeing the actual error that originally threw the exception, we are getting an error message from the failed 'ClientError' instantiation.

**To Reproduce**
I don't think you could reproduce this without using the same file we are trying to submit.

**Expected behavior**
Something is going wrong with the file submission, and we would expect to get an informative error message showing the actual cause of the problem.

**Environment (please complete the following information if pertinent):**
 - Assemblyline Version: [e.g. 4.3.0]
 - assemblyline-client 4.5.0

**Comment by gdesmar** [comment]
Could you confirm that the error happens on line 42 of assemblyline_client/assemblyline_client/v4_client/module/search/stream.py ?

**Comment by robthew** [comment]
This the stacktrace I'm seeing. The 'api_util.py' is using the client.
```
Error: __init__() missing 1 required positional argument: 'status_code'
/home/app_user/api_util.py: 89
/usr/local/lib/python3.8/site-packages/assemblyline_client/v4_client/module/submit.py: 83
/usr/local/lib/python3.8/site-packages/assemblyline_client/__init__.py: 163
/usr/local/lib/python3.8/site-packages/assemblyline_client/__init__.py: 231
```

**Comment by gdesmar** [comment]
Release 4.5.1 of the Assemblyline client was completed yesterday. Sorry for the delay. I'll go ahead and close this ticket as it should be fixed. Feel free to re-open it or contact us if it is not the case!
