### ISSUE TITLE
add support for only retrieving direct children from /api/v4/file/children/<sha256>/ 

### ISSUE THREAD

**Issue by ed4wg** [CybercentreCanada/assemblyline#65]
**Is your feature request related to a problem? Please describe.**
The `/api/v4/file/children/<sha256>/` api gives you all children recursively. Given the context of retrieving a `child` file, this was not expected behavior. 

**Describe the solution you'd like**
To keep the API backwards compatible, add an option to the API that allows you to only retrieve the direct children of a given file hash. Also update the api docs to indicate the default retrieval is a recursive view of all child files extracted.

**Comment by ed4wg** [comment]
After some further testing, it seems like there may also be a bug in the existing implementation.

Here's an example submission tree where i noticed an issue.
fileA
- fileA.1
    - fileA.1.1
    - fileA.1.2
- fileA.2
- fileA.3

Assuming the above file submission tree, i called the `/api/file/children` in the following scenarios:

Scenario 1 - retrieve children for fileA
- it returned fileA.1, fileA.2, and fileA.3 - all the direct children. In the service's current form, i would have expected all files to be returned, including fileA.1.1 and fileA.1.2.

Scenario 2 - retrieve children for fileA.1
- it returned fileA.1.1 and fileA.1.2 as expected


Testing another sample with a bigger hierarchy, of the 14 child files (various child/grandchild+) represented in the UI tree view, only 6 were returned when requesting the children for that root file. The 6 files returned were at various levels of the tree. All of the direct children, a grand-child, and great-great-grand-child in this case. 

I have observed that all direct children of a file seem to always be represented. It's everything below the child file that seems to be sporadic.

**Comment by cccs-sgaron** [comment]
We'll add a direct_children_only param to the API that will default to false not breaking current behavior and allowing to get only the direct children.

**Comment by cccs-rs** [comment]
After taking a look at our [/api/v4/file/children/](https://github.com/CybercentreCanada/assemblyline-ui/blob/a6b12011f8ddc7aa6690ac7229c6734b4128b582/assemblyline_ui/api/v4/file.py#L446), it seems that the API does in fact only return the direct children of the file based on the results generated about that file given.

The file tree view that you see in the UI (generated by `/api/v4/submission/tree/<sid>/`), does prune duplicate files (even at differing levels) from the original tree so it's possible to see more direct children through the `/api/v4/file/children/<sha256>` API than what's shown in the UI.

**Comment by gdesmar** [comment]
As @cccs-rs was pointing out, like your first fileA example is showing in both scenario 1 and scenario 2, only direct children are returned from the `file/children/<sha256>` API.

Regarding that second scenario:
> Testing another sample with a bigger hierarchy, of the 14 child files (various child/grandchild+) represented in the UI tree view, only 6 were returned when requesting the children for that root file. The 6 files returned were at various levels of the tree. All of the direct children, a grand-child, and great-great-grand-child in this case.
> 
> I have observed that all direct children of a file seem to always be represented. It's everything below the child file that seems to be sporadic.

The grand and great-great-grand-children that show up are also children of your original file. If you still have an example to test it on, could you go to `https://your-instance/file/detail/<sha256>`? You would see the list of Possible Children, among which should be all of the expected direct children, plus the two "unexpected" ones, for a total of six. They should be direct children of your file, and you should be able to find them from one of the service result underneath.

If you go to `https://your-instance/file/detail/<unexpected-child-sha256>`, you should see in the Possible Parents section your original file, and other(s) that should be part of your original submission, under which it showed up in the file tree. If you then go to those other parents, you should see that unexpected-child-sha256 as part of their children.

In your original submission, you will have the file tree at the bottom, but the submission view does some work to prune duplicate files to alleviate the tree. It shows only once even if the same file/same hash is a child of two different files. You should be able, from the submission view, to click on your original/submitted file, and go through all the results to see the 6 extracted files.

Regarding that API, another situation that could be unexpected would be:
Submission A, sending file A with a certain set of services that extracted 3 files.
Submission B, sending file A (same) with a completely different set of services that extract 4 different files.
By looking at the detail view of file A, you should see 7 Possible Children, even if by looking at any submission, you only see 3 or 4.
The API will therefore return the list of 7 files, as they are all possible children of your file.

I hope the API is clearer now. :)

**Comment by ed4wg** [comment]
Thanks for the helpful explanation! I now understand the behavior i was seeing and will go ahead and close this out.
