### ISSUE TITLE
Feature Request: Submission should leave an audit trail

### ISSUE THREAD

**Issue by ociappara** [CybercentreCanada/assemblyline#73]
**Is your feature request related to a problem? Please describe.**
In cases where a URL has been submitted but failed to fetch anything assemblyline leaves no audit trail, however, security tools might report that assemblyline infrastructure reached out to a suspicious domain, without an audit trails we are blind if this was a user trying to submit a URL to Assemblyline and failed or something nefarious.

**Describe the solution you'd like**
Create an audit trail that logs any submission made to Assemblyline, successful or otherwise.

**Comment by cccs-sgaron** [comment]
We also needed this internally but will extend this to files as well.

**Comment by cccs-sgaron** [comment]
Should be fixed with this PR: https://github.com/CybercentreCanada/assemblyline-ui/pull/637

I changed a lot of what was audited and not, you can review this a bit if you'd like.

**Comment by cccs-rs** [comment]
Fixed in [Release 4.4.0.21](https://github.com/CybercentreCanada/assemblyline/releases/tag/v4.4.0.stable21)
