### ISSUE TITLE
Add X.Y.stable tags for service components

### ISSUE THREAD

**Issue by HedgehogRidingAnOwl** [CybercentreCanada/assemblyline#76]
**Is your feature request related to a problem? Please describe.**
As is, there is no supported way during the bootstrap process to ensure all containers (core and service) are on compatible versions. Core components have a `X.Y.stable` tag that ensures latest stable versions up to the point of breaking changes while service containers have `stable` versions that can be breaking relative to core components. 

**Describe the solution you'd like**
Modify build pipelines to include pushing service versions with an `X.Y.stable` tag. 

**Describe alternatives you've considered**
- Using a more precise version number for services in the bootstrap process (e.g. 4.3.0.stable0). There's no guarantee every service will have at least one version # in common, leaving some services disabled on startup. This also doesn't allow for any non-breaking version increases, slowing down our adoption of new changes.  
- Telling my developers and users to be aware of this when an instance is deployed and to check version numbers first in the event services don't enable on start. This has a low success rate. 

**Additional context**
Referring to conversation on the AL discord server: 
https://discord.com/channels/908084610158714900/908717441771794472/1107745614567051345

**Comment by cccs-rs** [comment]
All service build pipelines have been updated to produce a "series" tag of the form `X.Y.(stable|latest)`.

We've also updated/added a means to specifying the service image version upon bootstrap in both Helm and Docker Compose, with the default value set to `4.4.stable`.

If you notice any services missing this new series tag, do let us know!
