### ISSUE TITLE
Feature Request: Time-Bound Safelisting

### ISSUE THREAD

**Issue by ociappara** [CybercentreCanada/assemblyline#82]
**Is your feature request related to a problem? Please describe.**
In our current system, once an IP address or domain is safelisted, it remains in that state indefinitely. This poses a significant security risk, as an entity that is deemed safe today may potentially turn into a security threat in the future.

**Describe the solution you'd like**
The introduction of an expiration mechanism for the safelisting of IPs, domains and other safelist entries. Users should have the ability to set a predefined expiration date on safelisted items at the time of entry, and edit it after. After the set period, the system should automatically revoke the safelisted status, prompting a review of the given entity for integrity.

**Comment by cccs-rs** [comment]
We could possibly introduce a field similar to a TTL that can be user-defined (if not defined, it will use a system-configured default).

Should the safelisted item reach expiration based on the TTL, we could disable the item from the system.
As for the component that should do this, I believe `expiry` is best suited since it handles expiration of other items in the system.

**Comment by cccs-sgaron** [comment]
Yup if we add `expiry_ts` field to safelist and monitor the safelist with expiry this can be easily done.

**Comment by cccs-sgaron** [comment]
We need to apply this to badlist as well.

This is what we will do to action this:
- Add expiry_ts to safelist as an optional date
- Add expiry_ts to badlist as an optional date
- Patch the APIs so if no dates are provided files never expire but Tag get a "configurable in config.yaml" expiry_ts value (e.g. 30 days)
- Make sure the expiry_ts date is overrideable through the Frontend when adding tags to badlist of safelist
- Make sure the expiry_ts date is modifiable when viewing a specific item in the Frontend

This needs to be done in sync with : https://github.com/CybercentreCanada/assemblyline/issues/144

**Comment by cccs-sgaron** [comment]
Fixed with the following PR:
https://github.com/CybercentreCanada/assemblyline-base/pull/1465
https://github.com/CybercentreCanada/assemblyline-ui/pull/793
https://github.com/CybercentreCanada/assemblyline-ui-frontend/pull/894

**Comment by kam193** [comment]
Hey, I see that the expiration setting is available when adding an element through Bad-/Safelist UI, but not when using contextual pop-up e.g. on the results page. Is it an intentional limitation?

**Comment by cccs-sgaron** [comment]
We can revisit that later, it felt crowed when adding tag because I essentially add to have every piece of editable information available. You can edit the expiry after the fact in the management page.
