### ISSUE TITLE
API Vector shows error when trying to pull malpedia

### ISSUE THREAD

**Issue by ociappara** [CybercentreCanada/assemblyline#83]
**Describe the bug**
Trying to pull https://malpedia.caad.fkie.fraunhofer.de/api/list/apiscout/csv in APIVector but keep getting the below error

**Status: stat: path should be string, bytes, os.PathLike or integer, not list**

**Comment by gdesmar** [comment]
I get the same error if I don't configure the API key. I'll assume that if you go in the service configuration (Administration -> Services -> APIVector), and into the UPDATES tab, you will see the following `<REPLACE_ME>`?
![image](https://github.com/CybercentreCanada/assemblyline/assets/75089569/e3c998ad-388e-4a57-93f5-00eeb81d0dd2)

If you have a Malpedia account, you can generate your apikey in your settings, as per https://malpedia.caad.fkie.fraunhofer.de/usage/api. As far as I know, Malpedia accounts are free, but needs to be created/validated by the owners of Malpedia themselves.

I'll leave this ticket open until I make the error more explicit on that missing configuration. Hopefully that was your issue.

**Comment by gdesmar** [comment]
There should be a newer version of APIVector that will give you a nicer error in the UI: 4.4.0.stable18 and 4.4.1.dev22.
I was wondering if you found anything in the logs that would point me toward the issue?
Thank you!

**Comment by cccs-rs** [comment]
Closing issue. If this is still a problem, feel free to re-open.
