### ISSUE TITLE
TagCheck Status: nothing to repeat at position 0

### ISSUE THREAD

**Issue by ociappara** [CybercentreCanada/assemblyline#84]
**Describe the bug**
Trying to pull TagCheck from https://assemblyline-support.s3.amazonaws.com/tagcheck.rules but keep getting the below error;
Status: nothing to repeat at position 0

I tried to delete the service and recreated it but I get the same error.

**Comment by cccs-rs** [comment]
A quick fix is to add `.*tagcheck\.rules` as the default pattern for the source. I will create a PR that should fix this.

**Comment by cccs-rs** [comment]
Should be resolved in v4.4.0.stable12
