### ISSUE TITLE
Custom username field for OAuth integration

### ISSUE THREAD

**Issue by scottpas** [CybercentreCanada/assemblyline#88]
**Is your feature request related to a problem? Please describe.**
Organisations may have existing usernames that aren't derived from user's email addresses. For auditing and identification purposes, allowing these usernames to be synced to AL when using OAuth would be helpful.

**Describe the solution you'd like**
Instead of relying on the email address or a random string for the AL username, an additional provider configuration option to specify a value from the OAuth token (e.g. uid, sub, samAccountName, etc.) would be greatly appreciated.
Additionally, if it is desired, a fallback to email address formatting or random usernames could be added if the requested value is not found.

**Describe alternatives you've considered**
There does not appear to be an alternative way to provide a custom username. Only random usernames or ones based off email addresses are currently allowed for OAuth.

**Additional context**
N/A

**Comment by cccs-sgaron** [comment]
Will be fixed by: 
https://github.com/CybercentreCanada/assemblyline-base/pull/1266
https://github.com/CybercentreCanada/assemblyline-ui/pull/684
