### ISSUE TITLE
Feature Request: Administrators should be able to export Assemblyline Safelist

### ISSUE THREAD

**Issue by ociappara** [CybercentreCanada/assemblyline#92]
**Is your feature request related to a problem? Please describe.**

As we get more users onboarded to the system and different services our Safelist will get better and different sources will start contributing to building our Safelist, it would be great if we could have an export feature to pull the entire Safelist out of Assemblyline so that it can be used by other sources.

**Describe the solution you'd like**

An API or UI feature that allows us to pull the entire Safelist from Assemblyline and save it in a databases outside of Assemblyline to be leveraged by other systems. Alternatively, a function which connects the safelist to an Event Hub, or database directly so when things are added and removed from Assemblyline Safelist they are automatically reflected in the external source.

**Comment by cccs-rs** [comment]
Just for clarity's sake:
Are we talking about exporting the safelist data found under `/manage/safelist` and/or the tag safelist under `/admin/tag_safelist`?

**Comment by ociappara** [comment]
I had the `/manage/safelist/` in mind for this feature.

**Comment by cccs-rs** [comment]
Should be part of the 4.5 release of Assemblyline via Replay:
https://github.com/CybercentreCanada/assemblyline/releases/tag/v4.5.0.stable1
