### ISSUE TITLE
Feature Request: Highlight Tags with Related Results

### ISSUE THREAD

**Issue by ociappara** [CybercentreCanada/assemblyline#93]
**Is your feature request related to a problem? Please describe.**

As an analyst using the current version of the platform, it can be time-consuming to identify which tags have related results. The only available method is to manually right-click each tag and select "Find Related Results", which can be a bottleneck in workflow efficiency.

**Describe the solution you'd like**

A more efficient and user-friendly approach would be to have a visual indicator - such as highlighting or a different colour - for tags that have related results. This would instantly inform users which tags can be utilized to pivot on, eliminating the need to individually check each tag through different sources.

**Describe alternatives you've considered**

An alternative solution might include a hover-over feature that shows the number of related results to a tag. However, this could still be more time-consuming than the preferred solution of colour-coding or highlighting tags with related results.

**Comment by cccs-sgaron** [comment]
This may completely take down the system. Some files generate hundreds of tags which we would have to perform individual queries for each to see if they are found in other results. I'm not sure how we could acheive this without having the UI being very very slow to load and without putting too much pressure on elastic. If you have any ideas, I'm all ears.

**Comment by ociappara** [comment]
Thanks @cccs-sgaron, this makes sense, I don't see an easy solution, feel free to close this case. If I think of something I'll bring it up.
