### ISSUE TITLE
Submisson of file

### ISSUE THREAD

**Issue by Scopemetadata** [CybercentreCanada/assemblyline#95]
Submission of file keeps running for an 86 mb file. its been 30 mins, I am on single appliance through docker

**Comment by cccs-rs** [comment]
Is the file stuck on a certain service in your appliance?

**Comment by cccs-rs** [comment]
Are there any logs from those containers to indicate an issue?

**Comment by Scopemetadata** [comment]
I can see in dashboard, these two characterize and floss being red but only for a second in Q section i can characterize shows Q 22
and Floss Q 8

but APKAY is red since the installation.

**Comment by cccs-rs** [comment]
If you'd like, you can join our Discord community (just a faster way of messaging and other members of the community might be able to help as well): https://discord.gg/GUAy9wErNu

You should be able to get the logs from the container using `docker logs -f <container_name>`

**Comment by cccs-rs** [comment]
Closing issue. If the issue still persists, feel free to reopen the issue.
